NomicFoundation/hardhat-ignition

README.md, examples/uniswap/.eslintrc.js, examples/uniswap/.gitignore, examples/uniswap/.prettierignore, examples/uniswap/README.md, examples/uniswap/contracts/Florin.sol, examples/uniswap/contracts/Solidus.sol, examples/uniswap/contracts/Uniswap.sol, examples/uniswap/contracts/WETH9.sol, examples/uniswap/hardhat.config.js, examples/uniswap/ignition/Uniswap.js, examples/uniswap/package.json, examples/uniswap/test/helpers.js, examples/uniswap/test/uniswap-test.js, packages/hardhat-plugin/package.json, yarn.lock
Add a uniswap example based on the `uniswap-v3-deployer`.
=> docs: add a uniswap example

README.md, docs/creating-modules-for-deployment.md, docs/using-ignition-in-hardhat-tests.md
Just did a run through of the docs and made a few small grammatical changes.
=> docs proofreading

packages/core/src/types/future.ts, packages/core/src/utils/guards.ts, packages/core/src/utils/proxy.ts, packages/core/src/validation/dispatch/helpers.ts
fixing a bug that didn't properly map dependencies when sending ETH
=> Fix for sendETH graphing

packages/hardhat-plugin/src/plan/assets/bundle.ts, packages/hardhat-plugin/src/plan/assets/main.css, packages/hardhat-plugin/src/plan/assets/templates/summary.html, packages/hardhat-plugin/src/plan/assets/templates/vertex.html, packages/hardhat-plugin/src/plan/index.ts, packages/hardhat-plugin/src/plan/utils.ts
added `value` field in vertex info page and made the whole thing a bit more stable and future-proof
=> Fixed plan task for send and event vertexes

docs/manual.md, packages/core/src/types/future.ts, packages/core/src/utils/guards.ts, packages/core/src/utils/proxy.ts, packages/core/src/validation/dispatch/helpers.ts, packages/hardhat-plugin/src/plan/assets/bundle.ts, packages/hardhat-plugin/src/plan/assets/main.css, packages/hardhat-plugin/src/plan/assets/templates/summary.html, packages/hardhat-plugin/src/plan/assets/templates/vertex.html, packages/hardhat-plugin/src/plan/index.ts, packages/hardhat-plugin/src/plan/utils.ts
Add a smoke test suite as a markdown doc under `./docs/manual.md`
Closes #94
=> docs: add manual test suite

packages/hardhat-plugin/package.json, packages/hardhat-plugin/src/index.ts, yarn.lock
=> Confirm deploy to non-hardhat network

docs/creating-modules-for-deployment.md, docs/running-a-deployment.md, examples/create2/ignition/Create2FactoryModule.js, examples/multisig/README.md, examples/multisig/ignition/MultisigModule.js, packages/core/src/Ignition.ts, packages/core/src/dsl/DeploymentBuilder.ts, packages/core/src/execution/dispatch/executeAwaitedEvent.ts, packages/core/src/types/deployment.ts, packages/core/src/types/deploymentGraph.ts, packages/core/src/validation/dispatch/validateEvent.ts, packages/core/src/validation/dispatch/validationDispatch.ts, packages/core/test/deploymentBuilder/event.ts, packages/core/test/execution/rerun.ts, packages/core/test/validation.ts, packages/hardhat-plugin/src/index.ts, packages/hardhat-plugin/test/config.ts, packages/hardhat-plugin/test/fixture-projects/with-config/hardhat.config.js
=> refactored awaitEvent to just event

packages/core/src/execution/dispatch/executeContractCall.ts, packages/core/src/execution/dispatch/executeContractDeploy.ts, packages/core/src/execution/dispatch/executeLibraryDeploy.ts, packages/core/src/execution/dispatch/executeSendETH.ts, packages/core/test/execution/rerun.ts
=> Catch potential error when confirming tx

examples/create2/package.json, examples/ens/package.json, examples/multisig/package.json, examples/sample/package.json, examples/uniswap/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/hardhat-plugin/CHANGELOG.md, packages/hardhat-plugin/package.json
- Resolve parameter args for deployed contracts during execution ([#125](https://github.com/NomicFoundation/ignition/pull/125))
=> chore: bump version to v0.0.7

.gitignore
Just adding a Webstorm folder to the root `.gitignore`
=> Ignore Webstorm files

examples/create2/package.json, examples/ens/package.json, examples/multisig/package.json, examples/sample/package.json, examples/ts-sample/package.json, examples/uniswap/package.json, package-lock.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/hardhat-plugin/CHANGELOG.md, packages/hardhat-plugin/package.json
- Make Hardhat network accounts available within modules ([#166](https://github.com/NomicFoundation/ignition/pull/166))
- Show file/line/column against validation errors, so that module problems can more easily be traced back to the source code ([#160](https://github.com/NomicFoundation/ignition/pull/160))
=> chore: bump version to v0.0.10

CONTRIBUTING.md, docs/distributable-deployments.md
Still WIP, but a design doc to outline what we want from distributable deployments and how we might go about doing it.
This is part of #90
=> docs: distributable deployments design doc

examples/create2/package.json, examples/ens/package.json, examples/multisig/package.json, examples/sample/package.json, examples/ts-sample/package.json, examples/uniswap/package.json, package-lock.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/hardhat-plugin/CHANGELOG.md, packages/hardhat-plugin/package.json
- Support recursive types in `m.call` args ([#186](https://github.com/NomicFoundation/ignition/issues/186))
=> chore: bump version to v0.0.12

docs/creating-modules-for-deployment.md, packages/core/src/internal/dsl/DeploymentBuilder.ts, packages/core/src/internal/execution/dispatch/executeStaticContractCall.ts, packages/core/src/internal/execution/dispatch/executionDispatch.ts, packages/core/src/internal/execution/dispatch/utils.ts, packages/core/src/internal/process/transform/convertDeploymentVertexToExecutionVertex.ts, packages/core/src/internal/types/deploymentGraph.ts, packages/core/src/internal/types/executionGraph.ts, packages/core/src/internal/utils/guards.ts, packages/core/src/internal/utils/proxy.ts, packages/core/src/internal/validation/dispatch/helpers.ts, packages/core/src/internal/validation/dispatch/validateStaticCall.ts, packages/core/src/internal/validation/dispatch/validationDispatch.ts, packages/core/src/types/dsl.ts, packages/core/src/types/future.ts, packages/core/test/deploymentBuilder/staticCalls.ts, packages/core/test/validation.ts, packages/hardhat-plugin/src/plan/utils.ts, packages/hardhat-plugin/src/ui/components/execution/FinalStatus.tsx, packages/hardhat-plugin/src/ui/types.ts
=> Implementing static calls

packages/core/src/internal/dsl/DeploymentBuilder.ts, packages/core/src/internal/types/deploymentGraph.ts, packages/core/src/internal/types/executionGraph.ts, packages/core/src/types/dsl.ts, packages/core/src/types/future.ts, packages/core/test/deploymentBuilder/event.ts
=> allow HardhatContracts for events

packages/core/src/new-api/internal/module-builder.ts, packages/core/src/new-api/internal/module.ts, packages/core/src/new-api/types/module-builder.ts, packages/core/src/new-api/types/module.ts, packages/core/test/new-api/contract.ts, packages/core/test/new-api/contractFromArtifact.ts, packages/core/test/new-api/library.ts, packages/core/test/new-api/libraryFromArtifact.ts
=> Library support in new api (New API PR 3)

packages/core/src/new-api/internal/module-builder.ts, packages/core/src/new-api/internal/module.ts, packages/core/src/new-api/types/module-builder.ts, packages/core/src/new-api/types/module.ts, packages/core/test/new-api/call.ts, packages/core/test/new-api/staticCall.ts
=> Call and static call support in new API (New API PR 4)

packages/core/src/new-api/internal/module-builder.ts, packages/core/src/new-api/types/module-builder.ts, packages/core/src/new-api/types/module.ts, packages/core/test/new-api/call.ts, packages/core/test/new-api/contract.ts, packages/core/test/new-api/contractAt.ts, packages/core/test/new-api/contractFromArtifact.ts, packages/core/test/new-api/library.ts, packages/core/test/new-api/libraryFromArtifact.ts, packages/core/test/new-api/staticCall.ts, packages/core/test/new-api/useModule.ts
=> Add chainId to new API (New API PR 6)

packages/core/src/new-api/internal/module-builder.ts, packages/core/src/new-api/types/module-builder.ts, packages/core/test/new-api/call.ts, packages/core/test/new-api/contract.ts, packages/core/test/new-api/contractAt.ts, packages/core/test/new-api/contractFromArtifact.ts, packages/core/test/new-api/library.ts, packages/core/test/new-api/libraryFromArtifact.ts, packages/core/test/new-api/staticCall.ts, packages/core/test/new-api/useModule.ts
=> Add accounts to new API (New API PR 7)

packages/core/src/new-api/internal/module-builder.ts, packages/core/src/new-api/internal/module.ts, packages/core/src/new-api/stored-deployment-serializer.ts, packages/core/src/new-api/types/module-builder.ts, packages/core/src/new-api/types/module.ts, packages/core/src/new-api/types/serialized-deployment.ts, packages/core/test/new-api/call.ts, packages/core/test/new-api/contract.ts, packages/core/test/new-api/contractFromArtifact.ts, packages/core/test/new-api/library.ts, packages/core/test/new-api/libraryFromArtifact.ts, packages/core/test/new-api/staticCall.ts
Added `value` and `from` as options to relevant futures
fixes #221
=> Add value and from to new API

packages/core/src/new-api/internal/module-builder.ts, packages/core/src/new-api/internal/module.ts, packages/core/src/new-api/stored-deployment-serializer.ts, packages/core/src/new-api/types/module-builder.ts, packages/core/src/new-api/types/module.ts, packages/core/src/new-api/types/serialized-deployment.ts, packages/core/test/new-api/send.ts, packages/ui/src/pages/future-details/components/future-summary.tsx, packages/ui/src/pages/plan-overview/components/action.tsx, packages/ui/src/utils/to-mermaid.ts
=> Add send to new API

examples/complete/ignition/CompleteModule.js, packages/core/src/new-api/internal/execution/execution-engine.ts, packages/core/src/new-api/internal/execution/transactions/transaction-service.ts, packages/core/src/new-api/internal/utils/collectLibrariesAndLink.ts, packages/core/src/new-api/types/transaction-service.ts, packages/core/test/new-api/execution/execution-engine.ts
=> Include contractFromArtifact in execution (PR 2)

examples/complete/ignition/CompleteModule.js, packages/core/src/new-api/internal/execution/execution-engine.ts
=> Include libraryFromArtifact in execution (PR 3)

examples/complete/ignition/CompleteModule.js, packages/core/src/new-api/internal/execution/execution-engine.ts, packages/core/src/new-api/internal/execution/execution-strategy.ts, packages/core/src/new-api/internal/execution/executionStateReducer.ts, packages/core/src/new-api/internal/execution/guards.ts, packages/core/src/new-api/internal/execution/transactions/transaction-service.ts, packages/core/src/new-api/internal/journal/type-guards.ts, packages/core/src/new-api/internal/types/execution-state.ts, packages/core/src/new-api/types/journal.ts
=> Include `m.send` in execution (PR 10)

examples/complete/ignition/CompleteModule.js, packages/core/src/new-api/internal/execution/execution-engine.ts, packages/core/src/new-api/internal/execution/execution-strategy.ts, packages/core/src/new-api/internal/execution/executionStateReducer.ts, packages/core/src/new-api/internal/execution/guards.ts, packages/core/src/new-api/internal/execution/transactions/transaction-service.ts, packages/core/src/new-api/internal/journal/type-guards.ts, packages/core/src/new-api/internal/reconciliation/futures/reconcileArtifactContractAt.ts, packages/core/src/new-api/internal/reconciliation/futures/reconcileNamedContractAt.ts, packages/core/src/new-api/internal/type-guards.ts, packages/core/src/new-api/internal/types/execution-state.ts, packages/core/src/new-api/internal/utils/resolve-future-to-value.ts, packages/core/src/new-api/types/journal.ts, packages/core/test/new-api/reconciliation/futures/reconcileArtifactContractAt.ts, packages/core/test/new-api/reconciliation/futures/reconcileNamedContractAt.ts
=> Include `m.contractAt` and `m.contractAtFromArtifact` in execution (PR 11)

packages/core/src/new-api/deploy.ts, packages/core/src/new-api/internal/deployment-loader/ephemeral-deployment-loader.ts, packages/core/src/new-api/internal/deployment-loader/file-deployment-loader.ts, packages/core/src/new-api/internal/execution/guards.ts, packages/core/src/new-api/internal/journal/file-journal.ts, packages/core/src/new-api/internal/journal/memory-journal.ts, packages/core/src/new-api/internal/journal/utils/log.ts, packages/hardhat-plugin/src/ignition-helper.ts, packages/hardhat-plugin/src/index.ts
- adds a `--logs` flag to `npx hardhat deploy2 ...` that enables logging journal write operations to the CLI
fixes #248
=> Output journal logs to CLI

packages/core/src/new-api/internal/deployer.ts, packages/core/src/new-api/internal/utils/retrieve-nested-runtime-values.ts, packages/core/src/new-api/internal/validation/futures/validateArtifactContractAt.ts, packages/core/src/new-api/internal/validation/futures/validateArtifactContractDeployment.ts, packages/core/src/new-api/internal/validation/futures/validateArtifactLibraryDeployment.ts, packages/core/src/new-api/internal/validation/futures/validateNamedContractAt.ts, packages/core/src/new-api/internal/validation/futures/validateNamedContractCall.ts, packages/core/src/new-api/internal/validation/futures/validateNamedContractDeployment.ts, packages/core/src/new-api/internal/validation/futures/validateNamedLibraryDeployment.ts, packages/core/src/new-api/internal/validation/futures/validateNamedStaticCall.ts, packages/core/src/new-api/internal/validation/futures/validateReadEventArgument.ts, packages/core/src/new-api/internal/validation/futures/validateSendData.ts, packages/core/src/new-api/internal/validation/validate.ts, packages/core/test/new-api/call.ts, packages/core/test/new-api/contract.ts, packages/core/test/new-api/contractAt.ts, packages/core/test/new-api/contractAtFromArtifact.ts, packages/core/test/new-api/contractFromArtifact.ts, packages/core/test/new-api/library.ts, packages/core/test/new-api/readEventArgument.ts, packages/core/test/new-api/send.ts, packages/core/test/new-api/staticCall.ts, packages/core/test/new-api/useModule.ts
=> Add validation for module params (PR 2)

packages/core/src/new-api/internal/execution/execution-engine.ts, packages/core/src/new-api/internal/module-builder.ts, packages/core/src/new-api/internal/module.ts, packages/core/src/new-api/internal/reconciliation/futures/reconcileArtifactContractDeployment.ts, packages/core/src/new-api/internal/reconciliation/futures/reconcileNamedContractCall.ts, packages/core/src/new-api/internal/reconciliation/futures/reconcileNamedContractDeployment.ts, packages/core/src/new-api/internal/reconciliation/futures/reconcileSendData.ts, packages/core/src/new-api/internal/validation/futures/validateArtifactContractAt.ts, packages/core/src/new-api/internal/validation/futures/validateArtifactContractDeployment.ts, packages/core/src/new-api/internal/validation/futures/validateNamedContractAt.ts, packages/core/src/new-api/internal/validation/futures/validateNamedContractCall.ts, packages/core/src/new-api/internal/validation/futures/validateNamedContractDeployment.ts, packages/core/src/new-api/internal/validation/futures/validateSendData.ts, packages/core/src/new-api/stored-deployment-serializer.ts, packages/core/src/new-api/types/module-builder.ts, packages/core/src/new-api/types/module.ts, packages/core/src/new-api/types/serialized-deployment.ts, packages/core/test/new-api/call.ts, packages/core/test/new-api/contract.ts, packages/core/test/new-api/contractAt.ts, packages/core/test/new-api/contractAtFromArtifact.ts, packages/core/test/new-api/contractFromArtifact.ts, packages/core/test/new-api/send.ts, packages/core/test/new-api/stored-deployment-serializer.ts
=> Support `ModuleParameterRuntimeValue` for `value` options (PR 2)

packages/core/src/new-api/deploy.ts, packages/core/src/new-api/internal/deployer.ts, packages/core/src/new-api/internal/execution/execution-engine.ts, packages/core/src/new-api/internal/reconciliation/reconciler.ts, packages/core/src/new-api/internal/reconciliation/types.ts, packages/core/src/new-api/internal/types/execution-engine.ts, packages/core/src/new-api/internal/utils/resolve-module-parameter.ts, packages/core/src/new-api/internal/validation/validate.ts, packages/core/src/new-api/types/deployer.ts, packages/core/src/new-api/types/module.ts
=> Create type for DeploymentParams (PR 8)

packages/core/src/index.ts, packages/core/src/new-api/define-module.ts
=> export buildModule alias for defineModule (PR 11)

packages/core/src/new-api/internal/validation/futures/validateArtifactContractAt.ts, packages/core/src/new-api/internal/validation/futures/validateArtifactContractDeployment.ts, packages/core/src/new-api/internal/validation/futures/validateArtifactLibraryDeployment.ts, packages/core/src/new-api/internal/validation/futures/validateNamedContractAt.ts, packages/core/src/new-api/internal/validation/futures/validateNamedContractCall.ts, packages/core/src/new-api/internal/validation/futures/validateNamedContractDeployment.ts, packages/core/src/new-api/internal/validation/futures/validateNamedLibraryDeployment.ts, packages/core/src/new-api/internal/validation/futures/validateNamedStaticCall.ts, packages/core/src/new-api/internal/validation/futures/validateReadEventArgument.ts, packages/core/src/new-api/internal/validation/futures/validateSendData.ts, packages/core/src/new-api/internal/validation/validate.ts, packages/core/test/new-api/execution/execution-engine.ts, packages/core/test/new-api/helpers.ts
Found a bug in the validation code that caused it to only validate the first future of a deployment, and fixing that revealed another bug in the code for validating nested module parameters. Both bugs are fixed in this PR and all affected tests are updated as well.
=> Fix for validation bugs (PR 12)

examples/complete/test/Complete.js
=> added a simple test for complete example

packages/core/src/new-api/internal/execution/chain-dispatcher.ts, packages/core/src/new-api/internal/new-execution/libraries.ts, packages/core/src/new-api/internal/validation/futures/validateArtifactContractDeployment.ts, packages/core/src/new-api/internal/validation/futures/validateArtifactLibraryDeployment.ts, packages/core/src/new-api/internal/validation/futures/validateNamedContractCall.ts, packages/core/src/new-api/internal/validation/futures/validateNamedContractDeployment.ts, packages/core/src/new-api/internal/validation/futures/validateNamedLibraryDeployment.ts, packages/core/src/new-api/internal/validation/futures/validateNamedStaticCall.ts, packages/core/test/new-api/call.ts, packages/core/test/new-api/new-execution/libraries.ts, packages/core/test/new-api/staticCall.ts
=> Add artifact function name validation for call and static call (PR 1)

packages/core/src/new-api/internal/deployer.ts, packages/core/src/new-api/internal/new-execution/views/find-deployed-contracts.ts, packages/hardhat-plugin/test/contracts.ts, packages/hardhat-plugin/test/plan/index.ts
This is a hack to get integration tests back.
=> feat/minimal-results-response (PR 7)

packages/core/src/internal/module-builder.ts, packages/core/src/type-guards.ts, packages/core/src/types/module-builder.ts, packages/core/src/types/module.ts, packages/core/test/call.ts, packages/core/test/staticCall.ts
=> restrict calls and static calls to non library contracts

packages/core/src/internal/module-builder.ts, packages/core/src/internal/module.ts, packages/core/src/types/module-builder.ts, packages/core/src/types/module.ts, packages/core/test/readEventArgument.ts, packages/hardhat-plugin/test/events.ts, packages/hardhat-plugin/test/fixture-projects/minimal/contracts/Contracts.sol
=> add support for reading events from send data futures

package-lock.json, packages/hardhat-plugin/package.json, packages/hardhat-plugin/src/ui/VerboseEventHandler.ts
=> added chalk styling to simple-text-ui output

packages/hardhat-plugin/src/index.ts
=> Lazy load external packages within plugin (PR 2)

packages/core/src/internal/module-builder.ts
=> Add type validations for module builder params (PR 3)

packages/core/src/errors.ts, packages/core/src/internal/utils/adjacency-list.ts
A small follow up PR after #479
=> Centralized errors continuation

packages/core/src/batches.ts, packages/core/src/index.ts, packages/hardhat-plugin/src/index.ts, packages/hardhat-plugin/src/visualization/write-visualization.ts, packages/ui/scripts/generate-example-deployment-json.js, packages/ui/src/main.tsx, packages/ui/src/pages/visualization-overview/components/deployment-flow.tsx, packages/ui/src/pages/visualization-overview/components/execution-batches.tsx, packages/ui/src/pages/visualization-overview/components/future-batch.tsx, packages/ui/src/pages/visualization-overview/visualization-overview.tsx, packages/ui/src/utils/to-escaped-id.ts, packages/ui/src/utils/to-mermaid.ts
=> Add batching information to visualize (UI PR 3)

package-lock.json, packages/core/src/batches.ts, packages/core/src/index.ts, packages/hardhat-plugin/src/index.ts, packages/hardhat-plugin/src/visualization/write-visualization.ts, packages/ui/package.json, packages/ui/scripts/generate-example-deployment-json.js, packages/ui/src/main.css, packages/ui/src/main.tsx, packages/ui/src/pages/visualization-overview/components/deployment-flow.tsx, packages/ui/src/pages/visualization-overview/components/execution-batches.tsx, packages/ui/src/pages/visualization-overview/components/future-batch.tsx, packages/ui/src/pages/visualization-overview/visualization-overview.tsx, packages/ui/src/utils/to-escaped-id.ts, packages/ui/src/utils/to-mermaid.ts
=> UI: implement tooltips (UI PR 2)

docs/running-a-deployment.md
=> add section to the docs discussing source control tradeoffs

.github/workflows/ci.yml
Just a small PR making sure that core's `test:integrations` gets run
=> Run integration tests on the CI

packages/hardhat-plugin/src/utils/open.ts
=> fail gracefully if program to open visualize output is not available

config/typescript/tsconfig.json, package-lock.json, packages/core/package.json, packages/core/src/internal/journal/utils/deserialize-replacer.ts, packages/core/src/internal/journal/utils/serialize-replacer.ts, packages/hardhat-plugin/package.json
Our restructuring of error handling means we no longer pass error objects as results to messages. We can remove this dep.
Resolves #523.
=> chore: remove serialize error dep (PR 3)

packages/ui/src/utils/argumentTypeToString.tsx
=> fixed weird escaping in arguments list

packages/ui/src/components/socials/index.tsx, packages/ui/src/pages/visualization-overview/components/deployment-flow.tsx, packages/ui/src/pages/visualization-overview/components/execution-batches.tsx, packages/ui/src/pages/visualization-overview/components/future-batch.tsx, packages/ui/src/pages/visualization-overview/visualization-overview.tsx
=> Fix bug and hide diagram for modules containing only one future

packages/hardhat-plugin/src/index.ts, packages/hardhat-plugin/src/utils/shouldBeHardhatPluginError.ts
=> handle error thrown by status task

packages/hardhat-plugin/src/index.ts, packages/hardhat-plugin/src/ui/helpers/calculate-deployment-complete-display.ts, packages/hardhat-plugin/src/ui/helpers/calculate-deployment-status-display.ts, packages/hardhat-plugin/test/ui/helpers/calculate-deployment-complete-display.ts, packages/hardhat-plugin/test/ui/helpers/calculate-deployment-status-display.ts
Update the status commands UI to match the updates in the deploy command.
=> feat/update status UI

packages/core/src/errors-list.ts, packages/core/src/internal/execution/execution-engine.ts, packages/core/src/internal/module-builder.ts, packages/core/test/call.ts, packages/core/test/contract.ts, packages/core/test/contractFromArtifact.ts, packages/core/test/execution/nonce-management/get-nonce-sync-messages.ts, packages/core/test/library.ts, packages/core/test/libraryFromArtifact.ts, packages/core/test/send.ts, packages/core/test/staticCall.ts, packages/core/test/validations/id-rules.ts, packages/core/test/wipe.ts
In this PR I went through all the error messages, changing some of them so that they were easier to understand.
I also made sure that every mention of "Hardhat Ignition" has the "Hardhat".
WIP: There are many tests to adapt.
=> [WIP] Review error messages (PR 1)

packages/hardhat-plugin/src/ui/helpers/calculate-deploying-module-panel.ts, packages/hardhat-plugin/test/ui/helpers/calculate-batch-display.ts, packages/hardhat-plugin/test/ui/helpers/calculate-deploying-module-panel-display.ts, packages/hardhat-plugin/test/ui/helpers/calculate-deployment-complete-display.ts, packages/hardhat-plugin/test/ui/helpers/calculate-deployment-status-display.ts, packages/hardhat-plugin/test/ui/helpers/test-format.ts
Add the reconciliation warnings to the deploying panel.
Fixes #567
=> fix: reconciliation warnings (PR B)

packages/core/src/internal/execution/nonce-management/json-rpc-nonce-manager.ts, packages/hardhat-plugin/test/execution/rerun-after-kill.ts
Update the nonce storage to record based on sender.
Fixes #576
=> fix: update nonce storage on getNewNonce (PR B)

packages/hardhat-plugin/src/load-module.ts, packages/hardhat-plugin/test/load-module.ts
=> removed missing modules folder error

packages/hardhat-plugin/src/ui/helpers/calculate-deployment-complete-display.ts, packages/hardhat-plugin/src/ui/helpers/was-anything-executed.ts, packages/hardhat-plugin/src/ui/pretty-event-handler.ts, packages/hardhat-plugin/test/ui/helpers/calculate-deployment-complete-display.ts
=> Changed the rendered text for previously successful depoyment

examples/sample/scripts/bump.js, packages/core/src/internal/deployer.ts, packages/core/src/types/execution-events.ts, packages/hardhat-plugin/src/index.ts, packages/hardhat-plugin/src/ui/helpers/calculate-batch-display.ts, packages/hardhat-plugin/src/ui/helpers/calculate-deployment-complete-display.ts, packages/hardhat-plugin/src/ui/helpers/calculate-deployment-status-display.ts, packages/hardhat-plugin/src/ui/pretty-event-handler.ts, packages/hardhat-plugin/src/ui/types.ts, packages/hardhat-plugin/test/ui/helpers/calculate-batch-display.ts, packages/hardhat-plugin/test/ui/helpers/calculate-deploying-module-panel-display.ts, packages/hardhat-plugin/test/ui/helpers/calculate-deployment-complete-display.ts, packages/hardhat-plugin/test/ui/helpers/calculate-deployment-status-display.ts
=> Add fee bumping messaging to the UI

package-lock.json, package.json, packages/core/package.json, packages/hardhat-plugin/package.json
=> Upgrade TypeScript to v5 (PR 1)

packages/core/src/build-module.ts, packages/core/src/errors-list.ts, packages/core/src/internal/module-builder.ts, packages/core/test/validations/id-rules.ts, packages/hardhat-plugin/src/utils/shouldBeHardhatPluginError.ts
=> Validate that module id's are not duplicated

packages/core/src/internal/execution/future-processor/future-processor.ts, packages/core/test/execution/future-processor/named-contract-at-deploy.ts, packages/core/test/execution/future-processor/named-contract-deploy.ts
=> Record contractAt addresses to json file

packages/core/src/ignition-module-serializer.ts, packages/core/src/internal/execution/future-processor/helpers/build-initialize-message-for.ts, packages/core/src/internal/execution/future-processor/helpers/future-resolvers.ts, packages/core/src/internal/execution/utils/address.ts, packages/core/src/internal/module-builder.ts, packages/core/src/internal/module.ts, packages/core/src/internal/reconciliation/futures/reconcileSendData.ts, packages/core/src/types/module-builder.ts, packages/core/src/types/module.ts, packages/core/src/types/serialization.ts, packages/core/test/contractAt.ts, packages/core/test/contractAtFromArtifact.ts, packages/core/test/ignition-module-serializer.ts, packages/core/test/readEventArgument.ts, packages/core/test/reconciliation/futures/reconcileSendData.ts, packages/core/test/send.ts, packages/core/test/validations/id-rules.ts
=> Allow sending to AccountRuntimeValue

packages/core/src/errors-list.ts, packages/core/src/internal/execution/jsonrpc-client.ts, packages/core/test-integrations/new-api/internal/new-execution/jsonrpc-client.ts, packages/hardhat-plugin/src/utils/shouldBeHardhatPluginError.ts
fixes #594 
screenshot (with redacted file system info in stack trace):
=> Catch base fee error and rethrow as ignition error

packages/core/src/deploy.ts, packages/hardhat-plugin/src/index.ts, packages/hardhat-plugin/test/deploy/default-sender.ts, packages/hardhat-plugin/test/fixture-projects/minimal/contracts/Ownable.sol, packages/hardhat-plugin/test/fixture-projects/minimal/ignition/modules/OwnModule.js
=> Allow overriding default sender from cli

CONTRIBUTING.md
=> Add sections regarding branching and merge flow to contributing doc

package-lock.json, packages/hardhat-plugin-viem/package.json, packages/hardhat-plugin-viem/src/viem-ignition-helper.ts, packages/hardhat-plugin/package.json, packages/hardhat-plugin/test/test-helpers/test-ignition-helper.ts
resolves #692 
depends on the release of https://github.com/NomicFoundation/hardhat/pull/4875
=> Upgrade hardhat-viem and viem versions

packages/core/src/status.ts, packages/core/src/types/status.ts, packages/core/test/status.ts, packages/hardhat-plugin/src/ui/helpers/calculate-deployment-status-display.ts, packages/hardhat-plugin/test/ui/helpers/calculate-deployment-status-display.ts
=> Add chainId to status output

packages/core/src/deploy.ts, packages/core/src/internal/errors-list.ts, packages/core/src/internal/execution/jsonrpc-client.ts, packages/core/test-integrations/new-api/internal/new-execution/jsonrpc-client.ts, packages/hardhat-plugin/src/index.ts, packages/hardhat-plugin/src/type-extensions.ts, packages/hardhat-plugin/src/utils/shouldBeHardhatPluginError.ts
=> Add configurable limit for maxFeePerGas

packages/core/src/internal/execution/jsonrpc-client.ts, packages/core/test-integrations/new-api/internal/new-execution/jsonrpc-client.ts
This is a follow on from https://github.com/NomicFoundation/hardhat-ignition/pull/730
=> Support zero fees chains

.gitignore, CONTRIBUTING.md, package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/internal/errors-list.ts, packages/core/src/internal/execution/future-processor/handlers/send-transaction.ts, packages/core/src/internal/execution/future-processor/helpers/decode-simulation-result.ts, packages/core/src/internal/execution/future-processor/helpers/network-interaction-execution.ts, packages/core/src/internal/execution/utils/address.ts, packages/core/src/internal/reconciliation/helpers/reconcile-arguments.ts, packages/core/test/execution/future-processor/helpers/network-interaction-execution.ts, packages/core/test/reconciliation/futures/reconcileArtifactContractDeployment.ts, packages/core/test/reconciliation/futures/reconcileNamedContractCall.ts, packages/core/test/reconciliation/futures/reconcileNamedContractDeployment.ts, packages/core/test/reconciliation/futures/reconcileNamedStaticCall.ts, packages/hardhat-plugin-ethers/CHANGELOG.md, packages/hardhat-plugin-ethers/package.json, packages/hardhat-plugin-viem/CHANGELOG.md, packages/hardhat-plugin-viem/package.json, packages/hardhat-plugin/CHANGELOG.md, packages/hardhat-plugin/package.json, packages/hardhat-plugin/src/utils/shouldBeHardhatPluginError.ts, packages/hardhat-plugin/test/deploy/rerun/rerun-after-kill.ts, packages/ui/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
- Reconcile address parameters with mismatched casings ([#748](https://github.com/NomicFoundation/hardhat-ignition/pull/748))
- Display better error messages for insufficient funds ([#754](https://github.com/NomicFoundation/hardhat-ignition/pull/754))
=> Release: 0.15.4

packages/core/src/internal/execution/jsonrpc-client.ts, packages/core/test-integrations/new-api/internal/new-execution/jsonrpc-client.ts
resolves #764 
manually verified working on anvil
=> Fix: handle anvil `hardhat_setBalance` response for create2

packages/core/src/internal/utils/resolve-module-parameter.ts, packages/hardhat-plugin/test/module-parameters.ts
=> Add support for global module parameters
