NomicFoundation/hardhat-ignition

- docs/publish.md
- examples/create2/package.json
- examples/ens/package.json
- examples/sample/package.json
- examples/uniswap/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/hardhat-plugin/CHANGELOG.md
- packages/hardhat-plugin/package.json
Update the packages versions and changelogs for the `0.0.4 - 2022-11-22` release:
- Pass eth as `value` on deploy or call ([#60](https://github.com/NomicFoundation/ignition/pull/60))
- Pass parameters for `value` ([#66](https://github.com/NomicFoundation/ignition/pull/66))
- Support setting module params from JSON file ([#64](https://github.com/NomicFoundation/ignition/pull/64))
> release:2022-11-22

- docs/creating-modules-for-deployment.md
- examples/multisig/ignition/Multisig.js
- examples/multisig/package.json
- examples/multisig/test/Multisig.js
- packages/core/src/dsl/DeploymentBuilder.ts
- packages/core/src/execution/dispatch/executeAwaitedEvent.ts
- packages/core/src/execution/dispatch/utils.ts
- packages/core/src/process/transform/convertDeploymentVertexToExecutionVertex.ts
- packages/core/src/types/deploymentGraph.ts
- packages/core/src/types/executionGraph.ts
- packages/core/src/types/future.ts
- packages/core/src/types/module.ts
- packages/core/src/types/serialization.ts
- packages/core/src/utils/guards.ts
- packages/core/src/utils/proxy.ts
- packages/core/src/utils/serialize.ts
- packages/core/src/validation/dispatch/validateAwaitEvent.ts
- packages/core/src/validation/dispatch/validationDispatch.ts
- packages/core/test/deploymentBuilder/awaitedEvent.ts
- packages/core/test/execution.ts
- packages/core/test/validation.ts
- packages/hardhat-plugin/src/ignition-wrapper.ts
- yarn.lock
- `m.awaitEvent` now includes a `params` field in its returned future that can be used to pass resolved emitted values into other module builder functions(i.e. as args)
- values from the emitted event are resolved and returned as the result of the event future
> resolve AwaitFuture to emitted event args

- examples/create2/ignition/Create2FactoryModule.js
- examples/create2/test/create2.test.js
- packages/core/src/dsl/DeploymentBuilder.ts
- packages/core/src/types/deploymentGraph.ts
- packages/core/src/types/executionGraph.ts
- packages/core/src/types/future.ts
- packages/core/src/validation/dispatch/validateAwaitEvent.ts
- packages/core/src/validation/dispatch/validateDeployedContract.ts
- packages/core/test/validation.ts
- event param futures can now be passed as addresses to `m.contractAt`
- updated create2 example to use `m.contractAt`
** merge #77 first **
> Support event params in contractAt

- examples/create2/package.json
- examples/ens/package.json
- examples/multisig/package.json
- examples/sample/package.json
- examples/uniswap/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/hardhat-plugin/CHANGELOG.md
- packages/hardhat-plugin/package.json
Update the packages versions and changelogs for the `0.0.5 - 2022-12-20` release.
- Add params section to deploy display in cli ([#74](https://github.com/NomicFoundation/ignition/pull/74))
- Expose config for pollingInterval ([#75](https://github.com/NomicFoundation/ignition/pull/75))
- Support `getBytesForArtifact` in deployment api ([#76](https://github.com/NomicFoundation/ignition/pull/76))
- Support use of emitted event args as futures for later deployment api calls ([#77](https://github.com/NomicFoundation/ignition/pull/77))
- Support event params futures in `contractAt` ([#78](https://github.com/NomicFoundation/ignition/pull/78))
- Fix for planning on modules with deploys from artifacts ([#73](https://github.com/NomicFoundation/ignition/pull/73))
> chore: bump version to v0.0.5

- docs/creating-modules-for-deployment.md
- examples/multisig/contracts/Multisig.sol
- examples/multisig/ignition/Multisig.js
- packages/core/src/dsl/DeploymentBuilder.ts
- packages/core/src/execution/dispatch/executeSendETH.ts
- packages/core/src/execution/dispatch/executionDispatch.ts
- packages/core/src/process/transform/convertDeploymentVertexToExecutionVertex.ts
- packages/core/src/types/deploymentGraph.ts
- packages/core/src/types/executionGraph.ts
- packages/core/src/types/future.ts
- packages/core/src/utils/guards.ts
- packages/core/src/validation/dispatch/validateSendETH.ts
- packages/core/src/validation/dispatch/validationDispatch.ts
- packages/core/test/deploymentBuilder/awaitedEvent.ts
- packages/core/test/deploymentBuilder/sendETH.ts
- packages/core/test/execution.ts
- packages/core/test/validation.ts
- packages/hardhat-plugin/src/ui/components/execution/FinalStatus.tsx
- packages/hardhat-plugin/src/ui/types.ts
Support sending `ETH` to a contract without having to make a call/deploy:
```tsx
m.sendETH(exchange, {
value: ethers.utils.parseUnits("1"),
});
```
> added ability to send a normal ETH transaction

- .github/workflows/add-issue-to-project.yml
- .github/workflows/add-label-to-new-issue.yml
Automatically assign new issues and prs to the Ignition project. Add a triaging label as well.
> chore: add github project automations

- examples/sample/ignition/LockModule.js
- packages/core/package.json
- packages/core/src/Ignition.ts
- packages/core/src/deployment/Deployment.ts
- packages/core/src/deployment/deployStateReducer.ts
- packages/core/src/execution/execute.ts
- packages/core/src/execution/utils.ts
- packages/core/src/index.ts
- packages/core/src/types/deployment.ts
- packages/core/src/utils/serialize.ts
- packages/core/test/execution/rerun.ts
- packages/core/test/state-reducer/execution.ts
- packages/hardhat-plugin/src/CommandJournal.ts
- packages/hardhat-plugin/src/ignition-wrapper.ts
- packages/hardhat-plugin/src/ui/components/ReconciliationFailedPanel.tsx
- packages/hardhat-plugin/src/ui/components/index.tsx
- packages/hardhat-plugin/src/ui/renderToCli.tsx
- packages/hardhat-plugin/test/CommandJournal.ts
We intend to add a reconciliation phase to allow for small changes in modules between runs. For the moment we will ban all changes and report an error if any are found.
> fix: guard against reruns with changes

- docs/explanation.md
- docs/running-a-deployment.md
- examples/sample/ignition/LockModule.js
- packages/hardhat-plugin/src/ui/components/ReconciliationFailedPanel.tsx
Some snagging before the release:
* update rerun warning
* add notes in the docs about rerunning changed modules
> fix: grammar mistake in rerun warning and docs changes

- examples/create2/package.json
- examples/ens/package.json
- examples/multisig/package.json
- examples/sample/package.json
- examples/uniswap/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/hardhat-plugin/CHANGELOG.md
- packages/hardhat-plugin/package.json
- Support rerunning deployments that errored or went to on-hold on a previous run ([#70](https://github.com/NomicFoundation/ignition/pull/70))
- Support sending `ETH` to a contract without having to make a call/deploy ([#79](https://github.com/NomicFoundation/ignition/pull/79))
- Confirm dialog on deploys to non-hardhat networks ([#95](https://github.com/NomicFoundation/ignition/issues/95))
- Rename the `awaitEvent` action in the api to `event` ([#108](https://github.com/NomicFoundation/ignition/issues/108))
> chore: bump version to v0.0.6

- docs/getting-started-guide.md
- examples/sample/ignition/LockModule.js
- packages/hardhat-plugin/src/ignition-wrapper.ts
The LockModule as taken from the HH quickstart changes the input time based on the time it is run. This was taken over but causes an issue on rerunning a deployment as the one of the module parameters has changed.
The sample project was previously changed to use a specific time in the example, this commit applies the same change to the quick start guide.
Fixes https://github.com/NomicFoundation/ignition/issues/133.
Includes a bonus bug fix to re-enable display of module params in the cli ui.
> docs: fix lock example in quickstart

- .github/workflows/ci.yml
- examples/create2/package.json
- examples/ens/package.json
- examples/multisig/package.json
- examples/sample/package.json
- examples/uniswap/package.json
- package-lock.json
- package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/hardhat-plugin/CHANGELOG.md
- packages/hardhat-plugin/package.json
- Allow file paths to ignition modules on cli to support cli completions for file discovery  ([#102](https://github.com/NomicFoundation/ignition/issues/102))
- Rename config option `gasIncrementPerRetry` to `gasPriceIncrementPerRetry` for clarity ([#143](https://github.com/NomicFoundation/ignition/pull/143))
- Improve error messages display during module validation ([#141](https://github.com/NomicFoundation/ignition/issues/141))
- Ban passing async functions to `buildModule` ([#138](https://github.com/NomicFoundation/ignition/issues/138))
> chore: bump version to v0.0.8

- .vscode/launch.json
- docs/getting-started-guide.md
- docs/running-a-deployment.md
- package-lock.json
- packages/core/package.json
- packages/core/src/Ignition.ts
- packages/core/src/deployment/Deployment.ts
- packages/core/src/deployment/deployStateReducer.ts
- packages/core/src/execution/execute.ts
- packages/core/src/types/deployment.ts
- packages/core/test/execution/rerun.ts
- packages/core/test/state-reducer/execution.ts
- packages/hardhat-plugin/src/ignition-wrapper.ts
- packages/hardhat-plugin/src/index.ts
- packages/hardhat-plugin/test/CommandJournal.ts
Support `--force` on deploy to ignore previous deployment runs and start again as if from a clean deployment. The history in the journal is kept but each action in the execution graph will be executed.
Resolves #132.
> feat: force flag on deploy

- packages/hardhat-plugin/src/index.ts
Switch from network name to chain id for the warning check on deploying to real networks. We do not ask when:
* running ephemerally
* running in tests
* running against local node
Fixes #134.
> fix: change warning check to chain

- docs/publish.md
- examples/create2/package.json
- examples/ens/package.json
- examples/multisig/package.json
- examples/sample/package.json
- examples/ts-sample/package.json
- examples/uniswap/package.json
- package-lock.json
- package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/hardhat-plugin/CHANGELOG.md
- packages/hardhat-plugin/package.json
- Support defining modules in typescript ([#101](https://github.com/NomicFoundation/ignition/issues/101))
- Allow rerunning deployment while ignoring journal history through a `--force` flag ([#132](https://github.com/NomicFoundation/ignition/issues/132))
- Do not ask for confirmation when deploying to a hardhat node ([#134](https://github.com/NomicFoundation/ignition/issues/134))
> chore: bump version to v0.0.9

- packages/core/src/Ignition.ts
- packages/core/src/dsl/DeploymentBuilder.ts
- packages/core/src/index.ts
- packages/core/src/process/generateDeploymentGraphFrom.ts
- packages/core/src/types/deploymentGraph.ts
- packages/core/src/types/validation.ts
- packages/core/src/utils/errors.ts
- packages/core/src/validation/dispatch/helpers.ts
- packages/core/src/validation/dispatch/validateArtifactContract.ts
- packages/core/src/validation/dispatch/validateArtifactLibrary.ts
- packages/core/src/validation/dispatch/validateCall.ts
- packages/core/src/validation/dispatch/validateDeployedContract.ts
- packages/core/src/validation/dispatch/validateEvent.ts
- packages/core/src/validation/dispatch/validateHardhatContract.ts
- packages/core/src/validation/dispatch/validateHardhatLibrary.ts
- packages/core/src/validation/dispatch/validateSendETH.ts
- packages/core/src/validation/dispatch/validateVirtual.ts
- packages/core/src/validation/dispatch/validationDispatch.ts
- packages/core/src/validation/validateDeploymentGraph.ts
- packages/core/test/state-reducer/utils.ts
- packages/core/test/validation.ts
- packages/hardhat-plugin/src/buildIgnitionProvidersFrom.ts
- packages/hardhat-plugin/src/ignition-wrapper.ts
- packages/hardhat-plugin/src/ui/components/ValidationFailedPanel.tsx
Show the file/line/column against each validation error. The display allows cmd+click in the vscode terminal.
To support this we capture a potential validation error when the deployment builder action is called. These potential errors are passed to the validation phase, one for each vertex. If a validation check fails we use the pre-captured error so that the stack trace shows the correct point in the module.
We have to do some magic in IgnitionValidationError. Firstly we need to externally rewrite the stack via a function call `resetStackFrom`, this is because Hardhat Errors manipulate the  stack themselves. To allow calling a custom function on the error, we need to manipulate the prototype because ... javascript.
Resolves https://github.com/NomicFoundation/ignition/issues/87.
> improvement: validation errors

- config/eslint/.eslintrc.js
- package-lock.json
- packages/core/.eslintrc.js
- packages/core/package.json
- packages/core/src/utils/errors.ts
- packages/core/test/.eslintrc.js
Instead of throwing hh errors, we throw our own ignition core errors, this allows us to remove hardhat as a dependency. This is ideal as ignition core should not force you to use hardhat even implicitly.
Resolves #163.
> refactor(core): remove dep on hardhat

- packages/core/src/index.ts
- packages/hardhat-plugin/esbuild.js
- packages/hardhat-plugin/src/plan/assets/bundle.ts
- packages/hardhat-plugin/src/plan/assets/templates/vertex.html
- packages/hardhat-plugin/src/plan/index.ts
- packages/hardhat-plugin/src/plan/utils.ts
Enforce the vertex types support through the type system. Include the library vertexes as a type of deploy.
Change the templating to include the new type strings.
Fixes #131.
> fix: support lib vertexes in plan

- packages/core/src/helpers.ts
- packages/core/test/options.ts
- packages/hardhat-plugin/src/ignition-wrapper.ts
- packages/hardhat-plugin/test/config.ts
The ContractServices and TransactionServices exports were only for test use.
The existing test of config has been split, the integration tests have been reduced to very simple checks that we load options for Ignition properly. The config tests proper have been shifted to core but now only test from the `Ignition` object being initialized to the config options use. Combined these give _close_ to equivalent coverage.
Part of #171.
> refactor: remove export of individual services

- examples/create2/package.json
- examples/ens/package.json
- examples/multisig/package.json
- examples/sample/package.json
- examples/ts-sample/package.json
- examples/uniswap/package.json
- package-lock.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/hardhat-plugin/CHANGELOG.md
- packages/hardhat-plugin/package.json
- Replace `m.getBytesForArtifact("Foo")` with `m.getArtifact("Foo")` in the module api ([#155](https://github.com/NomicFoundation/ignition/issues/155))
- Fix libraries in plan ([#131](https://github.com/NomicFoundation/ignition/issues/131))
> chore: bump version to v0.0.11

- packages/core/src/Ignition.ts
- packages/core/src/helpers.ts
- packages/core/test/execution/rerun.ts
- packages/core/test/helpers/getMockProviders.ts
- packages/core/test/helpers/getMockServices.ts
- packages/core/test/helpers/setupIgnitionWith.ts
- packages/core/test/helpers/setupIgnitionWithOverrideServices.ts
- packages/core/test/options.ts
- packages/hardhat-plugin/src/ignition-wrapper.ts
In place of services, pass providers then immediately convert them. This has the advantage of only exporting one set of concepts (i.e. low level providers) rather than two (providers and higher level services), particularly as one leverages the other.
The consequence of this approach though is that the providers are too low level for clean mocking in our core tests. The services are the more appropriate seam. By switching to providers in the `Ignition` constructor we lose that injection seam. This has been worked around with a utility function that sets up Ignition but overrides the services so that mocked services can continue to be used in tests.
Part of #171.
> refactor: pass providers to Ignition constructor

- packages/core/src/dsl/DeploymentBuilder.ts
- packages/core/src/index.ts
- packages/core/src/internal/process/transform/convertDeploymentVertexToExecutionVertex.ts
- packages/core/src/internal/types/executionGraph.ts
- packages/core/src/types/dsl.ts
- packages/core/test/deploymentBuilder/calls.ts
- packages/hardhat-plugin/test/calls.ts
- packages/hardhat-plugin/test/fixture-projects/minimal/contracts/Contracts.sol
Support arrays of bools, numbers and strings as args in `m.call`.
Fixes #186.
> fix: support arrays as arg option on call

- examples/create2/package.json
- examples/ens/package.json
- examples/multisig/package.json
- examples/sample/package.json
- examples/ts-sample/package.json
- examples/uniswap/package.json
- package-lock.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/hardhat-plugin/CHANGELOG.md
- packages/hardhat-plugin/package.json
- Support static calls in the Module API ([#85](https://github.com/NomicFoundation/ignition/issues/85))
- Add command, `ignition-info`, to list previously deployed contracts ([#111](https://github.com/NomicFoundation/ignition/issues/111))
> chore: bump version to v0.0.13

- docs/creating-modules-for-deployment.md
- packages/core/src/internal/dsl/DeploymentBuilder.ts
- packages/core/src/internal/types/deploymentGraph.ts
- packages/core/src/internal/utils/guards.ts
- packages/core/src/internal/validation/dispatch/helpers.ts
- packages/core/src/internal/validation/dispatch/validateArtifactLibrary.ts
- packages/core/src/internal/validation/dispatch/validateCall.ts
- packages/core/src/internal/validation/dispatch/validateEvent.ts
- packages/core/src/internal/validation/dispatch/validateHardhatLibrary.ts
- packages/core/src/internal/validation/dispatch/validateStaticCall.ts
- packages/core/src/types/future.ts
- packages/core/test/deploymentBuilder/parameters.ts
- packages/core/test/deploymentBuilder/useModule.ts
- packages/core/test/validation.ts
There are currently some incorrect assumptions made about libraries that aren't harming anything, per se, but we should refactor them for clarity regardless.
fixes #177
> Library Refactor

- packages/core/src/new-api/define-module.ts
- packages/core/src/new-api/examples.ts
- packages/core/test/new-api/call.ts
- packages/core/test/new-api/contract.ts
- packages/core/test/new-api/contractAt.ts
- packages/core/test/new-api/contractFromArtifact.ts
- packages/core/test/new-api/library.ts
- packages/core/test/new-api/libraryFromArtifact.ts
- packages/core/test/new-api/staticCall.ts
- packages/core/test/new-api/useModule.ts
- packages/hardhat-plugin/src/ui/components/execution/ModuleParameters.tsx
Rename `buildModule` to `defineModule` to help clarify the mental steps.
> refactor/rename build module define module (new api PR 8)

- packages/core/src/new-api/internal/batcher.ts
- packages/core/src/new-api/types/execution-state.ts
- packages/core/test/new-api/batcher.ts
Add a batcher that will take an IgnitionModule and (mocked) extension state map and return a set of batches for later execution.
> new batching (New API PR 10)

- packages/core/src/index.ts
- packages/core/src/new-api/internal/module-builder.ts
- packages/core/src/new-api/stubs.ts
- packages/core/src/new-api/types/module-builder.ts
- packages/core/src/new-api/types/module.ts
- packages/core/test/new-api/getParameter.ts
Included both required and optional parameters in the same implementation because it seemed like a clean and simple solution to me. Happy to refactor back to just the `getOptioinalParam` version if we prefer separate implementations like in the old API. 
fixes #226
> add getParameter to new API

- packages/core/src/new-api/internal/module-builder.ts
- packages/core/src/new-api/internal/module.ts
- packages/core/src/new-api/stored-deployment-serializer.ts
- packages/core/src/new-api/types/execution-state.ts
- packages/core/src/new-api/types/module-builder.ts
- packages/core/src/new-api/types/module.ts
- packages/core/src/new-api/types/serialized-deployment.ts
- packages/core/test/new-api/contractAt.ts
- packages/core/test/new-api/contractAtFromArtifact.ts
- packages/core/test/new-api/stored-deployment-serializer.ts
- packages/ui/src/pages/future-details/components/future-summary.tsx
- packages/ui/src/pages/plan-overview/components/action.tsx
- packages/ui/src/types.ts
- packages/ui/src/utils/to-mermaid.ts
- added support for passing static call futures into `contractAt` as an address
- added named and artifact variants for `contractAt` futures
- updated plan UI to handle new features
fixes #225
> Support passing futures as addresses in contractAt

- packages/core/src/new-api/internal/module-builder.ts
- packages/core/src/new-api/internal/module.ts
- packages/core/src/new-api/stored-deployment-serializer.ts
- packages/core/src/new-api/types/execution-state.ts
- packages/core/src/new-api/types/module-builder.ts
- packages/core/src/new-api/types/module.ts
- packages/core/src/new-api/types/serialized-deployment.ts
- packages/core/test/new-api/readEventArgument.ts
- packages/core/test/new-api/stored-deployment-serializer.ts
- packages/ui/src/pages/future-details/components/future-summary.tsx
- packages/ui/src/pages/plan-overview/components/action.tsx
- packages/ui/src/types.ts
- packages/ui/src/utils/to-mermaid.ts
This PR adds ModuleBuilder#readEventArgument.
It also fixes an error message that I believe got outdated due to a merging order issue.
I intentionally left out of this PR using the values read by these futures, as I think that requires some work across the whole module api.
> Add readEventArgument action

- packages/core/src/new-api/internal/execution/execution-engine.ts
- packages/core/src/new-api/internal/execution/execution-strategy.ts
- packages/core/src/new-api/internal/execution/executionStateReducer.ts
- packages/core/src/new-api/internal/execution/guards.ts
- packages/core/src/new-api/internal/execution/transactions/transaction-service.ts
- packages/core/src/new-api/internal/reconciliation/execution-state-resolver.ts
- packages/core/src/new-api/internal/reconciliation/futures/reconcileArtifactContractDeployment.ts
- packages/core/src/new-api/internal/reconciliation/futures/reconcileArtifactLibraryDeployment.ts
- packages/core/src/new-api/internal/reconciliation/futures/reconcileNamedContractCall.ts
- packages/core/src/new-api/internal/reconciliation/futures/reconcileNamedContractDeployment.ts
- packages/core/src/new-api/internal/reconciliation/futures/reconcileNamedLibraryDeployment.ts
- packages/core/src/new-api/internal/reconciliation/futures/reconcileNamedStaticCall.ts
- packages/core/src/new-api/internal/reconciliation/futures/reconcileSendData.ts
- packages/core/src/new-api/internal/types/execution-engine.ts
- packages/core/src/new-api/internal/types/execution-state.ts
- packages/core/src/new-api/internal/utils/resolve-from-address.ts
- packages/core/src/new-api/types/journal.ts
- packages/core/test/new-api/execution/execution-engine.ts
- packages/core/test/new-api/reconciliation/futures/reconcileArtifactContractAt.ts
- packages/core/test/new-api/reconciliation/futures/reconcileArtifactContractDeployment.ts
- packages/core/test/new-api/reconciliation/futures/reconcileArtifactLibraryDeployment.ts
- packages/core/test/new-api/reconciliation/futures/reconcileNamedContractAt.ts
- packages/core/test/new-api/reconciliation/futures/reconcileNamedContractCall.ts
- packages/core/test/new-api/reconciliation/futures/reconcileNamedContractDeployment.ts
- packages/core/test/new-api/reconciliation/futures/reconcileNamedLibraryDeployment.ts
- packages/core/test/new-api/reconciliation/futures/reconcileNamedStaticCall.ts
- packages/core/test/new-api/reconciliation/futures/reconcileReadEventArgument.ts
- packages/core/test/new-api/reconciliation/futures/reconcileSendData.ts
- packages/core/test/new-api/reconciliation/reconciler.ts
In execution state the `from` address should always be set. If the future specifies undefined, this should be reconcilied as `account[0]` the same way it is during execution.
Fixes #281
> fix: execution state from should always be set (PR 6)

- docs/creating-modules-for-deployment.md
- examples/complete/ignition/CompleteModule.js
- package-lock.json
- packages/core/src/new-api/deploy.ts
- packages/core/src/new-api/internal/execution/execution-engine.ts
- packages/core/src/new-api/internal/execution/execution-strategy.ts
- packages/core/src/new-api/internal/execution/executionStateReducer.ts
- packages/core/src/new-api/internal/execution/guards.ts
- packages/core/src/new-api/internal/execution/transactions/chain-dispatcher.ts
- packages/core/src/new-api/internal/execution/transactions/transaction-service.ts
- packages/core/src/new-api/internal/journal/type-guards.ts
- packages/core/src/new-api/internal/types/execution-state.ts
- packages/core/src/new-api/type-guards.ts
- packages/core/src/new-api/types/journal.ts
- packages/core/src/new-api/types/module.ts
- packages/core/test/new-api/reconciliation/futures/reconcileArtifactContractAt.ts
- packages/core/test/new-api/reconciliation/futures/reconcileNamedContractAt.ts
- packages/core/test/new-api/reconciliation/futures/reconcileNamedContractCall.ts
- packages/core/test/new-api/reconciliation/futures/reconcileNamedStaticCall.ts
- Added support for `m.call(...)` execution
- Added support for `m.staticCall(...)` execution
- Moved `signerAdapter` and contract-specific logic from `ChainDispatcher` to `TransactionService`
fixes #264
> Include Call in Execution (PR 7)

- examples/sample/contracts/Lock.sol
- packages/core/src/index.ts
- packages/core/src/new-api/internal/deployer.ts
- packages/core/src/new-api/internal/execution/execution-engine.ts
- packages/core/src/new-api/internal/execution/execution-strategy.ts
- packages/core/src/new-api/internal/execution/executionStateReducer.ts
- packages/core/src/new-api/internal/execution/guards.ts
- packages/core/src/new-api/internal/execution/transactions/chain-dispatcher.ts
- packages/core/src/new-api/internal/execution/transactions/transaction-service.ts
- packages/core/src/new-api/internal/journal/memory-journal.ts
- packages/core/src/new-api/internal/journal/type-guards.ts
- packages/core/src/new-api/internal/wiper.ts
- packages/core/src/new-api/types/deployer.ts
- packages/core/src/new-api/types/journal.ts
- packages/core/src/new-api/wipe.ts
- packages/core/test/new-api/call.ts
- packages/core/test/new-api/contract.ts
- packages/core/test/new-api/contractAt.ts
- packages/core/test/new-api/contractFromArtifact.ts
- packages/core/test/new-api/execution/execution-engine.ts
- packages/core/test/new-api/execution/restart.ts
- packages/core/test/new-api/helpers.ts
- packages/core/test/new-api/library.ts
- packages/core/test/new-api/readEventArgument.ts
- packages/core/test/new-api/staticCall.ts
- packages/core/test/new-api/wipe.ts
- packages/hardhat-plugin/src/index.ts
Support restarting a run after a failed future (i.e. a future that has a transaction that reverts).
A `wipe` cli command has been added to allow reruns on error by clearing
the state against a future:
```sh
npx hardhat wipe --deployment network-31337 --future LockModule:Lock
```
> feat/restart-on-error (PR 8)

- examples/complete/ignition/CompleteModule.js
- packages/core/src/new-api/internal/execution/execution-engine.ts
- packages/core/src/new-api/internal/execution/execution-strategy.ts
- packages/core/src/new-api/internal/execution/executionStateReducer.ts
- packages/core/src/new-api/internal/execution/guards.ts
- packages/core/src/new-api/internal/execution/transactions/chain-dispatcher.ts
- packages/core/src/new-api/internal/execution/transactions/transaction-service.ts
- packages/core/src/new-api/internal/journal/type-guards.ts
- packages/core/src/new-api/internal/reconciliation/execution-state-resolver.ts
- packages/core/src/new-api/internal/reconciliation/futures/reconcileReadEventArgument.ts
- packages/core/src/new-api/internal/types/execution-state.ts
- packages/core/src/new-api/types/adapters.ts
- packages/core/src/new-api/types/journal.ts
- packages/core/src/new-api/types/module.ts
- packages/core/test/new-api/execution/execution-engine.ts
- packages/core/test/new-api/execution/restart.ts
- packages/core/test/new-api/reconciliation/futures/reconcileReadEventArgument.ts
- packages/core/test/new-api/wipe.ts
- packages/hardhat-plugin/src/buildAdaptersFrom.ts
- support `m.readEventArgument` in execution engine
- support passing result of `m.readEventArgument` execution into other futures as arguments
fixes #266
> Include readEventArgument in execution (PR 9)

- packages/core/src/new-api/deploy.ts
- packages/core/src/new-api/internal/batcher.ts
- packages/core/src/new-api/internal/deployer.ts
- packages/core/src/new-api/internal/execution/execution-engine.ts
- packages/core/src/new-api/internal/execution/execution-state-reducer.ts
- packages/core/src/new-api/internal/execution/guards.ts
- packages/core/src/new-api/internal/execution/onchain-state-transitions.ts
- packages/core/src/new-api/internal/execution/transaction-lookup-timer.ts
- packages/core/src/new-api/internal/journal/type-guards.ts
- packages/core/src/new-api/internal/journal/utils/log.ts
- packages/core/src/new-api/internal/types/execution-engine.ts
- packages/core/src/new-api/internal/types/execution-state.ts
- packages/core/src/new-api/internal/types/transaction-timer.ts
- packages/core/src/new-api/types/deployer.ts
- packages/core/src/new-api/types/journal.ts
- packages/core/test/new-api/execution/execution-engine.ts
- packages/core/test/new-api/helpers.ts
- packages/hardhat-plugin/src/ignition-helper.ts
- packages/hardhat-plugin/src/index.ts
- packages/hardhat-plugin/test/execution/nonce-checks/useDeploymentDirectory.ts
- packages/hardhat-plugin/test/execution/timeouts/deploy-run-times-out.ts
- packages/hardhat-plugin/test/execution/timeouts/rerun-a-deploy-that-timed-out.ts
The timeout is checked on lookup of a pending transaction. If the configured timeout is passed then the future is moved to the `timeout` state via a message.
Resolves #293.
> execution/timeouts (PR F)

- packages/core/src/new-api/internal/execution/execution-engine.ts
- packages/core/src/new-api/internal/execution/execution-strategy.ts
- packages/core/src/new-api/internal/execution/onchain-state-transitions.ts
- packages/core/src/new-api/internal/utils/resolve-futures.ts
- packages/core/src/new-api/types/journal.ts
- packages/core/test/new-api/execution/execution-engine.ts
- packages/core/test/new-api/reconciliation/reconciler.ts
- packages/hardhat-plugin/test/fixture-projects/minimal-new-api/contracts/WithLibrary.sol
- packages/hardhat-plugin/test/libraries.ts
- packages/hardhat-plugin/test/use-ignition-project.ts
This fixes the deployment of contracts/libraries that need linked to other libraries.
This is done by resolving the library deps to the deployed libraries during the init command for execution state, then passing the library to contract address mapping into the deploy request messages.
> fix:library-deploy (PR H)

- packages/core/src/new-api/internal/deployer.ts
- packages/core/src/new-api/type-guards.ts
- packages/hardhat-plugin/test/execution/deploy-contract-at-from-artifact.ts
- packages/hardhat-plugin/test/execution/deploy-contract-at.ts
- packages/hardhat-plugin/test/execution/deploy-contract-from-artifact.ts
- packages/hardhat-plugin/test/execution/deploy-contract.ts
- packages/hardhat-plugin/test/execution/multiple-batch-contract-deploy.ts
Pre-artifact loading for the passed Ignition module should use the artifact resolved for named contracts, but read the artifacts from the passed future for user provided cases.
Two integration tests have been added that cover the bug.
> fix: artifact module loading (PR 3)

- packages/core/src/new-api/internal/deployer.ts
- packages/core/src/new-api/internal/deployment-loader/ephemeral-deployment-loader.ts
- packages/core/src/new-api/internal/deployment-loader/file-deployment-loader.ts
- packages/core/src/new-api/internal/execution/execution-engine.ts
- packages/core/src/new-api/internal/execution/execution-state-reducer.ts
- packages/core/src/new-api/internal/execution/execution-strategy-cycler.ts
- packages/core/src/new-api/internal/execution/execution-strategy.ts
- packages/core/src/new-api/internal/execution/guards.ts
- packages/core/src/new-api/internal/execution/onchain-action-reducer.ts
- packages/core/src/new-api/internal/execution/onchain-state-transitions.ts
- packages/core/src/new-api/internal/journal/file-journal.ts
- packages/core/src/new-api/internal/journal/memory-journal.ts
- packages/core/src/new-api/internal/journal/type-guards.ts
- packages/core/src/new-api/internal/journal/utils/log.ts
- packages/core/src/new-api/internal/types/deployment-loader.ts
- packages/core/src/new-api/internal/types/execution-engine.ts
- packages/core/src/new-api/internal/types/execution-state.ts
- packages/core/src/new-api/internal/types/journal.ts
- packages/core/src/new-api/internal/wiper.ts
- packages/core/src/new-api/type-guards.ts
- packages/core/src/new-api/types/deployment-loader.ts
- packages/core/test/new-api/helpers.ts
- packages/core/test/new-api/types/deployment-loader.ts
- packages/core/test/new-api/wipe.ts
> Deployment Loader Cleanup (PR 7)

- README.md
- docs/creating-modules-for-deployment.md
- docs/explanation.md
- docs/getting-started-guide.md
- docs/running-a-deployment.md
- docs/using-ignition-in-hardhat-tests.md
- examples/sample/ignition/LockModule.js
- examples/ts-sample/ignition/LockModule.ts
- packages/hardhat-plugin/src/index.ts
Update the docs to reflect the changes in the new api.
I had to re-export `buildModule` via `@ignored/hardhat-ignition` to get the previous behaviour.
Resolves #250.
> cleanup/update-docs (PR 13)

- packages/core/src/new-api/internal/execution/execution-engine.ts
- packages/hardhat-plugin/test/events.ts
- packages/hardhat-plugin/test/fixture-projects/minimal-new-api/contracts/Factory.sol
We were assuming either a deployment execution state or a contract at execution state when resolving the address of a contractAt future.
A check has been added to see if the address a readEventArg, and that it resolves to a valid address string.
Fixes #354.
> fix: allow readEventArg as address in contractAt

- examples/complete/package.json
- examples/ens/package.json
- examples/sample/package.json
- examples/ts-sample/package.json
- examples/uniswap/package.json
- package-lock.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/hardhat-plugin/CHANGELOG.md
- packages/hardhat-plugin/package.json
- packages/ui/package.json
- Fix validation error when using the result of a `readEventArgument` as the address of a `contractAt`/`contractAtFromArtifact` ([#354](https://github.com/NomicFoundation/ignition/issues/354))
> chore: bump version to v0.1.1

- packages/core/src/new-api/internal/execution/chain-dispatcher.ts
- packages/core/src/new-api/internal/execution/execution-engine.ts
- packages/hardhat-plugin/test/fixture-projects/minimal-new-api/contracts/Factory.sol
- packages/hardhat-plugin/test/static-calls.ts
A check has been added to see if the address a staticCall, and that it resolves to a valid address string.
Also fixed a bug in the static call execution code.
Fixes #357.
> fix: allow staticCall as address in contractAt(FromArtifact)

- examples/complete/package.json
- examples/ens/package.json
- examples/sample/package.json
- examples/ts-sample/package.json
- examples/uniswap/package.json
- package-lock.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/hardhat-plugin/CHANGELOG.md
- packages/hardhat-plugin/package.json
- packages/ui/package.json
- Fix validation error when using the result of a `staticCall` as the address of a `contractAt`/`contractAtFromArtifact` ([#354](https://github.com/NomicFoundation/ignition/issues/357))
- Fix bug in `staticCall` execution logic preventing successful execution
> chore: bump version to v0.1.2

- packages/hardhat-plugin/src/index.ts
- packages/hardhat-plugin/src/load-module.ts
- packages/hardhat-plugin/test/fixture-projects/user-modules/ignition/TestModule.js
- packages/hardhat-plugin/test/load-module.ts
> Rework module loading

- examples/complete/test/Complete.js
We are not auto-detecting auto-mining chains, which means tests need an explicit override.
This will be cleaned up in a coming commit.
> test: fix for complete test

- packages/core/src/new-api/internal/execution/chain-dispatcher.ts
- packages/core/src/new-api/internal/execution/execution-engine.ts
- packages/core/src/new-api/internal/execution/onchain-state-transitions.ts
- packages/core/src/new-api/internal/execution/types.ts
- packages/core/src/new-api/internal/journal/types/future-level-journal-message/future-start-message.ts
- packages/core/src/new-api/internal/journal/types/transaction-level-journal-message/onchain-interaction-message.ts
The main change here is switching to SolidityParameterType for args, this implied pushing that change through the messages and execution state. By the time an execution state is initialized the args should be resolved.
Fixes #380.
> refactor: clean up chain-dispatcher (PR 1)

- examples/complete/package.json
- examples/ens/package.json
- examples/sample/package.json
- examples/ts-sample/package.json
- examples/uniswap/package.json
- package-lock.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/hardhat-plugin/CHANGELOG.md
- packages/hardhat-plugin/package.json
- packages/ui/package.json
- The execution config is now exposed through deploy and wired into the `hardhat-ignition` plugin config.
- Switch default deploy configurations depending on whether the current network is automined.
> chore: bump version to v0.2.0

- packages/core/src/new-api/internal/execution/chain-dispatcher.ts
The ticket originally was for writing a more comprehensive solution for static call function names with args, but this is handled in validation now so this issue was largely resolved already. Just removing the temp fix now.
fixes #372
> Remove temp fix for static call function names (PR 2)

- docs/running-a-deployment.md
- examples/complete/test/Complete.js
- examples/ens/test/sample-test.js
- examples/sample/test/Lock.js
- examples/ts-sample/test/Lock.ts
- examples/uniswap/test/uniswap-test.js
- packages/core/src/new-api/deploy.ts
- packages/core/src/new-api/internal/deployer.ts
- packages/hardhat-plugin/test/config.ts
- packages/hardhat-plugin/test/fixture-projects/with-config/hardhat.config.js
- packages/hardhat-plugin/test/fixture-projects/with-invalid-config/hardhat.config.js
- packages/hardhat-plugin/test/load-module.ts
- packages/hardhat-plugin/test/type-helper.ts
Bring the config section of the docs inline with the new config values and the defaults.
Fix an issue with config and automining. The user provided `requiredConfirmations` should take precedence even over the automining default.
> docs/update-config-section (PR 6)

- packages/core/src/new-api/internal/new-execution/abi.ts
- packages/core/test/new-api/new-execution/abi.ts
- packages/hardhat-plugin/test/events.ts
This PR forbids using arguments with dynamic types as their values are hashed and used as topics, not stored.
It also fixes how the arguments are decoded, by providing ethers the topics and not just the data of the log.
It also re-enables the argument-related integration tests.
> Fix readEventArgument validation and decoding

- examples/complete/package.json
- examples/complete/test/Complete.js
- examples/ens/package.json
- examples/ens/test/sample-test.js
- examples/sample/hardhat.config.js
- examples/sample/package.json
- examples/sample/test/Lock.js
- examples/ts-sample/package.json
- examples/ts-sample/test/Lock.ts
- examples/uniswap/package.json
- examples/uniswap/test/helpers.js
- examples/uniswap/test/simplified-test.js
- examples/uniswap/test/uniswap-test.js
- package-lock.json
- packages/core/src/new-api/internal/new-execution/basic-execution-strategy.ts
Upgrade the samples to toolbox 3.0.0 so that ethers v6 is used throughout the monorepo.
This lets us bring back the samples, with the exception of the full uniswap test as the test depends on the uniswap sdk which is ethers v5 based. That test remains skipped but a simpler uniswap test has been added that asserts that the deploy has completed.
Includes a minor fix to the basic execution strategy to fix the `to` of send requests.
Resolves #421.
> chore: re-enable samples

- packages/core/src/new-api/internal/reconciliation/futures/reconcileSendData.ts
- packages/core/src/new-api/internal/reconciliation/helpers/reconcile-data.ts
- packages/core/test/new-api/reconciliation/futures/reconcileSendData.ts
Two runs where the send data is undefined now reconcile.
Fixes #420.
> fix: reconcile send data when undefined

- packages/core/src/new-api/internal/reconciliation/reconciler.ts
- packages/core/test/new-api/reconciliation/reconciler.ts
If a future has previously timed out or failed (not just failed at simulation). Then the user must wipe the future with the wipe command before rerunning.
We enforce this with a reconciliation check. This check comes after the future level reconciliation checks (a design decision we may revisit - could it just be a standard rule?).
Resolves #412.
> feat: reconciliation rule blocking timed out/failed futures

- packages/core/src/index.ts
- packages/core/src/new-api/internal/deployer.ts
- packages/core/src/new-api/internal/formatters.ts
- packages/core/src/new-api/internal/journal/utils/log.ts
- packages/core/src/new-api/internal/new-execution/future-processor/handlers/run-strategy.ts
- packages/core/src/new-api/internal/new-execution/types/execution-result.ts
- packages/core/src/ui-helpers.ts
- packages/core/test/new-api/new-execution/reducers/running-a-call.ts
- packages/core/test/new-api/new-execution/reducers/running-a-named-contract-deploy.ts
- packages/core/test/new-api/new-execution/reducers/running-send-data.ts
> Format the execution errors returned by deploy()

- packages/hardhat-plugin/src/ignition-helper.ts
- packages/hardhat-plugin/test/calls.ts
- packages/hardhat-plugin/test/config.ts
- packages/hardhat-plugin/test/execution/multiple-batch-contract-deploy.ts
- packages/hardhat-plugin/test/params.ts
- packages/hardhat-plugin/test/use-ignition-project.ts
The ignition-helper `deploy` function takes an options object, both config and parameters are now optional (providing one no longer requires the other).
> fix: support optional config/parameters in deploy

- packages/core/src/internal/execution/reducers/deployment-state-reducer.ts
- packages/core/src/internal/execution/types/messages.ts
- packages/core/src/internal/journal/utils/emitExecutionEvent.ts
- packages/core/src/internal/journal/utils/log.ts
- packages/core/src/internal/wiper.ts
- packages/core/src/types/execution-events.ts
- packages/hardhat-plugin/src/ui/UiEventHandler.tsx
- packages/hardhat-plugin/src/ui/VerboseEventHandler.ts
Rename the `WIPE_EXECUTION_STATE` message to `WIPE_APPLY`. This is because all other message follow a `NOUN_VERB_MESSAGE` structure, so we should follow it for wipe as well.
The problem with mentioning execution state is it suggests that we are dealing with a execution state level message. In reality `WIPE` is its own world.
> refactor: rename wipe message

- packages/core/src/internal/execution/execution-engine.ts
- packages/core/src/internal/execution/future-processor/future-processor.ts
- packages/core/src/internal/execution/future-processor/helpers/future-resolvers.ts
- packages/core/src/internal/execution/nonce-management.ts
- packages/core/src/internal/execution/reducers/helpers/network-interaction-helpers.ts
- packages/core/src/internal/views/execution-state/find-onchain-interaction-by.ts
- packages/core/src/internal/views/execution-state/find-static-call-by.ts
- packages/core/src/internal/views/execution-state/find-transaction-by.ts
- packages/core/src/internal/views/execution-state/get-pending-nonce-and-sender.ts
- packages/core/src/internal/views/execution-state/get-pending-onchain-interaction.ts
- packages/core/src/internal/views/find-address-for-contract-future-by-id.ts
- packages/core/src/internal/views/find-confirmed-transaction-by-future-id.ts
- packages/core/src/internal/views/find-deployed-contracts.ts
- packages/core/src/internal/views/find-execution-state-by-id.ts
- packages/core/src/internal/views/find-result-for-future-by-id.ts
- packages/core/src/internal/views/has-execution-failed.ts
- packages/core/src/internal/views/is-execution-state-complete.ts
- packages/core/test/execution/reducers/running-a-call.ts
- packages/core/test/execution/reducers/running-a-named-contract-deploy.ts
- packages/core/test/execution/reducers/running-a-named-library-deploy.ts
- packages/core/test/execution/reducers/running-a-read-event-arg.ts
- packages/core/test/execution/reducers/running-a-static-call.ts
- packages/core/test/execution/reducers/running-contract-at.ts
- packages/core/test/execution/reducers/running-send-data.ts
- packages/core/test/execution/views/find-result-for-future-by-id.ts
Views are used for execution state and more generally than just the execution phase.
> refactor: move views out of execution

- packages/hardhat-plugin/src/index.ts
Rename the parameter for deploy to avoid a clash with debugging functionality.
Resolves #443.
> feat: rename `use-verbose` to `simple-text-ui`

- packages/core/src/internal/module.ts
- packages/core/src/stored-deployment-serializer.ts
- packages/core/src/types/module.ts
Note, the linked issue says we currently accept `SendData` futures as `futureToReadFrom`, but we do not. Extra consideration would be needed to add it as an accepted type, so I've added a new issue to capture that discussion in #459
fixes #395
> restrict ReadEventArgumentFuture types for futureToReadFrom

- packages/core/src/internal/execution/execution-engine.ts
- packages/core/src/internal/execution/future-processor/future-processor.ts
- packages/core/src/internal/views/is-batch-finished.ts
- packages/core/test/execution/future-processor/named-contract-deploy.ts
Tweak the logic for determining whether to start the next batch so that it is derived from the deployment state.
Update the `uniswap` example hardhat config so that automining is off but confirmations aren't ridiculous:
```js
require("@nomicfoundation/hardhat-toolbox");
require("@ignored/hardhat-ignition");
/**
* @type import('hardhat/config').HardhatUserConfig
*/
module.exports = {
solidity: {
compilers: [
{
version: "0.5.5",
},
{
version: "0.7.6",
settings: {
optimizer: {
enabled: true,
runs: 800,
},
metadata: {
// do not include the metadata hash, since this is machine dependent
// and we want all generated code to be deterministic
// https://docs.soliditylang.org/en/v0.7.6/metadata.html
bytecodeHash: "none",
},
},
},
],
},
networks: {
hardhat: {
mining: {
auto: false,
interval: 3000, …
```
> fix: rework batch complete detection

- packages/core/src/internal/deployer.ts
- packages/core/src/types/deploy.ts
- packages/hardhat-plugin/src/ui/components/execution/FinalStatus.tsx
- packages/hardhat-plugin/src/utils/error-deployment-result-to-exception-message.ts
- packages/hardhat-plugin/test/utils/error-deployment-result-to-exception-message.ts
In deploy results we should use the correct concept name. ExecutionId was an old but related concept.
> refactor: rename executionId to networkInteractionId

- packages/core/src/internal/batcher.ts
- packages/core/src/internal/deployer.ts
- packages/core/src/internal/execution/execution-engine.ts
- packages/core/src/internal/execution/reducers/helpers/complete-execution-state.ts
- packages/core/src/internal/execution/types/execution-result.ts
- packages/core/src/internal/execution/types/execution-state.ts
- packages/core/src/internal/formatters.ts
- packages/core/src/internal/journal/utils/emitExecutionEvent.ts
- packages/core/src/internal/views/has-execution-succeeded.ts
- packages/core/src/types/deploy.ts
- packages/core/src/types/execution-events.ts
- packages/hardhat-plugin/src/ui/UiEventHandler.tsx
- packages/hardhat-plugin/src/ui/VerboseEventHandler.ts
- packages/hardhat-plugin/src/ui/components/execution/BatchExecution.tsx
- packages/hardhat-plugin/src/ui/types.ts
- packages/hardhat-plugin/src/utils/error-deployment-result-to-exception-message.ts
- packages/hardhat-plugin/test/utils/error-deployment-result-to-exception-message.ts
To support execution strategies returning `hold` status in the future,
we are adding it into the execution status of exStates.
Resolves https://github.com/NomicFoundation/ignition/issues/451
> feat: add `Held` status to exState status

- packages/core/src/internal/deployer.ts
- packages/core/src/internal/reconciliation/reconciler.ts
- packages/core/src/types/deploy.ts
- packages/core/test/reconciliation/reconciler.ts
- packages/hardhat-plugin/src/ui/components/execution/FinalStatus.tsx
- packages/hardhat-plugin/src/utils/error-deployment-result-to-exception-message.ts
- Moved logic for checking for previous run errors out of reconciliation flow
- Created a new `DeploymentResult` type to encapsulate the previous run errors
- Updated the UI to display more information to the user for the new `DeploymentResult` type (see screenshot)
fixes #431
> Refactor previous run timeout/failure check

- docs/creating-modules-for-deployment.md
- examples/complete/ignition/CompleteModule.js
- examples/uniswap/ignition/Uniswap.js
- packages/core/src/internal/module-builder.ts
- packages/core/src/types/module-builder.ts
- packages/core/test/call.ts
- packages/core/test/contractAtFromArtifact.ts
- packages/core/test/contractFromArtifact.ts
- packages/core/test/libraryFromArtifact.ts
- packages/core/test/readEventArgument.ts
- packages/core/test/reconciliation/futures/reconcileArtifactContractAt.ts
- packages/core/test/reconciliation/futures/reconcileArtifactContractDeployment.ts
- packages/core/test/reconciliation/futures/reconcileArtifactLibraryDeployment.ts
- packages/core/test/staticCall.ts
- packages/core/test/stored-deployment-serializer.ts
- packages/core/test/validations/id-rules.ts
- packages/hardhat-plugin/test/contracts.ts
- packages/hardhat-plugin/test/events.ts
- packages/hardhat-plugin/test/execution/deploy-contract-at-from-artifact.ts
- packages/hardhat-plugin/test/execution/deploy-contract-from-artifact.ts
- packages/hardhat-plugin/test/existing-contract.ts
- packages/hardhat-plugin/test/libraries.ts
- packages/hardhat-plugin/test/static-calls.ts
- packages/ui/test/to-mermaid.ts
> Module builder refactor: overload `contract`, `contractAt`, and `library`.

- packages/core/src/internal/deployment-loader/ephemeral-deployment-loader.ts
- packages/core/src/internal/deployment-loader/file-deployment-loader.ts
- packages/core/src/internal/deployment-loader/types.ts
- packages/core/src/internal/execution/future-processor/helpers/save-artifacts-for-future.ts
- packages/core/test/reconciliation/helpers.ts
If a build info is stored for a future id, record a debug file as a pointer. The debug file is a sibling to the artifact file, so under `./ignition/deployments/<depid>/artifacts`:
- `LockModule#Lock.json`
- `LockModule#Lock.dbg.json`
The dbg file points at the Ignition build info file via a relative path.
> feat: store debug files with build infos

- packages/core/src/internal/deployer.ts
- packages/core/src/types/execution-events.ts
- packages/hardhat-plugin/src/ui/UiEventHandler.tsx
- packages/hardhat-plugin/src/ui/VerboseEventHandler.ts
- packages/hardhat-plugin/src/ui/components/execution/ExecutionPanel.tsx
- packages/hardhat-plugin/src/ui/components/execution/Warnings.tsx
- packages/hardhat-plugin/src/ui/types.ts
> Show missing futures warnings in execution UI

- packages/core/src/ignition-module-serializer.ts
- packages/core/src/internal/execution/future-processor/helpers/build-initialize-message-for.ts
- packages/core/src/internal/execution/future-processor/helpers/future-resolvers.ts
- packages/core/src/internal/module-builder.ts
- packages/core/src/internal/module.ts
- packages/core/src/internal/reconciliation/helpers/reconcile-value.ts
- packages/core/src/types/module-builder.ts
- packages/core/src/types/module.ts
- packages/core/src/types/serialization.ts
- packages/core/test/contract.ts
- packages/core/test/ignition-module-serializer.ts
- packages/hardhat-plugin/test/contracts.ts
- packages/hardhat-plugin/test/fixture-projects/minimal/contracts/Contracts.sol
> Support using the result from `m.staticCall` or `m.readEventArgument` as value option

- packages/core/src/internal/reconciliation/helpers/reconcile-from.ts
- packages/core/test/reconciliation/futures/reconcileNamedContractCall.ts
- packages/core/test/reconciliation/futures/reconcileNamedContractDeployment.ts
- packages/core/test/reconciliation/futures/reconcileNamedStaticCall.ts
- packages/core/test/reconciliation/futures/reconcileSendData.ts
If a `from` is undefined on the first run, allow it to reconcile on the second run using the account that was selected during initialization of the future on the first run. This is only valid if the first run from account (the default sender on the first run) is still in the list of accounts.
Fixes #413.
> fix: allow undefined froms to pass reconciliation (PR 2)

- examples/ens/.gitignore
- packages/core/src/deploy.ts
- packages/core/src/internal/deployer.ts
- packages/core/src/internal/views/find-deployed-contracts.ts
- packages/core/src/types/deploy.ts
- packages/core/src/types/execution-events.ts
- packages/hardhat-plugin/src/ignition-helper.ts
- packages/hardhat-plugin/src/ui/UiEventHandler.tsx
- packages/hardhat-plugin/src/ui/components/execution/AddressResults.tsx
- packages/hardhat-plugin/src/ui/components/execution/FinalStatus.tsx
- packages/hardhat-plugin/src/ui/types.ts
The result was constrained to only those contracts returned by the module. It now returns all contracts and contractAts that have been deployed in this run and previous runs.
The `ignition-helper` now takes the responsibility of resolving the modules results to contracts (and only the result contracts).
Note the types have not been altered.
Resolves #480.
> fix: display all deployed contracts (PR 3)

- packages/core/src/internal/execution/execution-engine.ts
- packages/core/src/internal/execution/future-processor/future-processor.ts
- packages/core/src/internal/execution/future-processor/handlers/send-transaction.ts
- packages/core/src/internal/execution/nonce-management/get-max-nonce-used-by-sender.ts
- packages/core/src/internal/execution/nonce-management/get-nonce-sync-messages.ts
- packages/core/src/internal/execution/nonce-management/json-rpc-nonce-manager.ts
- packages/core/src/type-guards.ts
- packages/core/test/execution/future-processor/utils.ts
- packages/core/test/execution/nonce-management/get-nonce-sync-messages.ts
Include the future senders from the module when syncing nonces for checks. 
The senders for all futures without exStates that will be used if the module executes, are now added to the syncing taking into account usage of default sender when `from` is undefined.
Resolves #411
> fix/additional-nonces-checks (PR 7)

- packages/core/src/internal/execution/nonce-management/get-nonce-sync-messages.ts
- packages/core/test/execution/nonce-management/get-nonce-sync-messages.ts
There was a wrong check on whether the transactions against the last network interaction are still in the mempool. If at least one transaction is in the mempool we don't do the further checks that assume the transaction with that nonce has been either dropped or replaced by the user.
I have added a test for the failing case of rerun at the command line.
Fixes #506.
> fix: nonce-syncing check of mempool transactions (PR 8)

- packages/core/src/internal/execution/nonce-management/get-nonce-sync-messages.ts
- packages/core/test/execution/nonce-management/get-nonce-sync-messages.ts
If there are pending Ignition transactions, we still want to check if the user has sent additional transactions on top of that.
A test has been added to cover the case as well.
> feat/additional nonce sync check (PR 9)

- package-lock.json
- packages/hardhat-plugin/package.json
- packages/ui/package.json
Move the ui projects dependencies to dev-dependencies.
The UI npm package consists of a single `index.html` file that is used from the Ignition plugin. This is built during publishing. There is no need for any additional dependencies.
Resolves #521.
> chore: move UI deps to dev deps (PR 2)

- examples/complete/README.md
- examples/ens/README.md
- examples/sample/README.md
- examples/ts-sample/README.md
- packages/core/test-integrations/new-api/internal/reconciliation/chainId.ts
- packages/hardhat-plugin/src/index.ts
- packages/hardhat-plugin/src/load-module.ts
- packages/hardhat-plugin/test/load-module.ts
- packages/hardhat-plugin/test/plan/index.ts
We are removing support for invoking a module just by giving its file name. Instead the tasks will work in terms of a full or relative path to the module file.
Users prefer this for autocomplete reasons anyway, but it removes confusion as to whether it is the `ModuleId` or filename that is in use here.
Resolves #527.
> remove support for module file names in tasks

- examples/complete/ignition/modules/CompleteModule.js
- examples/ens/ignition/modules/ENS.js
- examples/ens/ignition/modules/test-registrar.js
- examples/sample/ignition/modules/LockModule.js
- examples/ts-sample/ignition/modules/LockModule.ts
- packages/core/test-integrations/fixture-projects/default-with-new-chain-id/ignition/modules/LockModule.js
- packages/hardhat-plugin/package.json
- packages/hardhat-plugin/src/index.ts
- packages/hardhat-plugin/src/modules.ts
We re-export `buildModule` in `hardhat-ignition` from a `modules` entry point to avoid clashes with Hardhat plugin setup. Now to setup a module you need to import:
```
import { buildModule } from "@nomicfoundation/hardhat-ignition/modules";
```
Resolves #540.
I created a the HH sample project in both js and ts modes and was able to leverage the new entrypoint.
> feat: expose `buildModule` on its own entry point

- packages/hardhat-plugin/src/index.ts
- packages/hardhat-plugin/src/utils/shouldBeHardhatPluginError.ts
- added error rethrowing to all tasks
- added two new error codes to the whitelist
- fixed a bug in the `wipe` task
fixes #543
> Add error rethrowing to all plugin tasks

- package-lock.json
- packages/hardhat-plugin/package.json
As we aren't asking the user to use core directly, there's no need for it to be a peer dependency. Making it a dependency leads to a simpler ux.
> Make ignition-core a dependency, and not a peerDependency

- packages/hardhat-plugin/src/ui/helpers/calculate-batch-display.ts
- packages/hardhat-plugin/src/ui/pretty-event-handler.ts
- packages/hardhat-plugin/src/ui/types.ts
Init events where overwriting the batch init for futures, and setting them to pending (aka timeout).
The fix is to set them to unstarted (the same as the batch init).
This fixes the flash of pending/timed out displayed for futures.
At the same time several of the future events have been updated to redisplay the batch. This is a separate bug, but fixing it makes the initial issue more obvious.
Fixes https://github.com/NomicFoundation/hardhat-ignition/issues/545.
> fix: timeout display

- packages/hardhat-plugin/src/ui/helpers/calculate-deploying-module-panel.ts
- packages/hardhat-plugin/src/ui/helpers/calculate-deployment-complete-display.ts
- packages/hardhat-plugin/src/ui/helpers/calculate-deployment-status-display.ts
- packages/hardhat-plugin/src/ui/pretty-event-handler.ts
- packages/hardhat-plugin/test/ui/helpers/calculate-deployment-complete-display.ts
- packages/hardhat-plugin/test/ui/helpers/calculate-deployment-status-display.ts
The blank line at the start is removed from both the `deploy` task display and also removed from `status` task displays.
Resolves #554.
> improvement: remove blank line from start of deploy (PR 1)

- examples/complete/ignition/modules/CompleteModule.js
- packages/core/src/internal/module-builder.ts
- packages/core/src/types/module-builder.ts
- packages/core/test/contractAtFromArtifact.ts
- packages/core/test/ignition-module-serializer.ts
- packages/core/test/reconciliation/futures/reconcileArtifactContractAt.ts
- packages/core/test/validations/id-rules.ts
- packages/hardhat-plugin/test/events.ts
- packages/hardhat-plugin/test/execution/deploy-contract-at-from-artifact.ts
- packages/hardhat-plugin/test/existing-contract.ts
- packages/hardhat-plugin/test/static-calls.ts
- packages/ui/test/to-mermaid.ts
Switch the `artifact` version of `contractAt` to:
```js
m.contractAt(name, artifact, address)
```
This brings it into line with other artifact based signatures.
Resolves #557.
> feat: change contractAt signature

- packages/hardhat-plugin/src/ui/helpers/calculate-deployment-complete-display.ts
- packages/hardhat-plugin/src/ui/helpers/calculate-deployment-status-display.ts
- packages/hardhat-plugin/test/ui/helpers/calculate-deployment-complete-display.ts
- packages/hardhat-plugin/test/ui/helpers/calculate-deployment-status-display.ts
Update the cli text based on the tweaks ui doc.
* update the status text for success
* update text of timed out futures
* update the failed text
* update status text for started futures
* don't expose strategy level information
This also updates the separators in the tests.
> improvement: update the text for status and completion

- packages/core/src/internal/module-builder.ts
- packages/core/src/internal/utils/future-id-builders.ts
- packages/core/test/utils/future-id-builders.ts
This PR introduces a small change that makes working with multiple instances of the same contract in a module easier.
> Define call ids based on the entire id of the contract being called, not just its name (PR 2)

- packages/core/src/errors.ts
- packages/hardhat-plugin/src/index.ts
- packages/hardhat-plugin/src/load-module.ts
- packages/hardhat-plugin/src/utils/shouldBeHardhatPluginError.ts
Before this PR validation errors weren't displaying their stack traces. This was problematic, as those are needed to be able to debug your errors. We intentionally construct stack traces that can be helpful for that in `core`.
After this PR, the plugin doesn't wrap those validation errors in a `HardhatPluginError`, instead, it prints them and throws a more basic plugin error.
While doing this, I introduce three small improvements:
* `IgnitionError` doesn't pass the `cause` property if it's undefined, as that interferes with Node's default error formatting.
* `IgnitionError` now has a `errorNumber` property, that can be used to check which error was thrown.
* When creating a plugin error, we pass the `cause`/`parent` error wherever appropriate.
> Better validation error messages

- packages/core/src/internal/module-builder.ts
- packages/core/src/internal/utils/future-id-builders.ts
- packages/core/src/internal/utils/identifier-validators.ts
- packages/core/test/utils/future-id-builders.ts
- packages/core/test/validations/id-rules.ts
This adds support for Fully Qualified Names (FQN) to be used as contract names. This is important, as Hardhat uses FQNs (e.g. `contracts/Foo.sol:Foo`) whenever a bare name (e.g. `Foo`) is duplicated.
To achieve this, I changed two things:
* If a future id is derived from a contract name, and the contract name is a FQN, we only use the contract name (e.g. `Foo` above) part of the FQN.
* If a FQN is used as a contract name, we only validate its contract name part.
> Support fully qualified contract names (PR 3)

- packages/core/src/internal/execution/nonce-management/get-nonce-sync-messages.ts
- packages/core/test/execution/nonce-management/get-nonce-sync-messages.ts
The future senders update the account to nonce+transactions list in such away that existing pending transactions for the account are untouched.
No test has been added, but the case has been covered by enhancing the example module to include an unexecuted future in the module.
Fixes #574.
> fix: stop future senders clearing out pending trans (PR A)

- packages/ui/src/utils/to-escaped-id.ts
- packages/ui/src/utils/to-mermaid.ts
- packages/ui/test/to-mermaid.ts
This PR introduces some small changes to the mermaid graph:
- It swaps the order of the graph, as when writing docs with Fran we noticed it was confusing in the top-to-bottom order, so I switched it to bottom-to-top
- I changed the function that escapes ids so that it escapes `~` because we are using them now, and also tweaked it a bit to try to avoid clashes.
- While doing this I realized that some ids weren't escaped, so i fixed that.
> Small mermaid fixes

- examples/complete/package.json
- examples/ens/package.json
- examples/sample/package.json
- examples/sample/scripts/bump.js
- examples/ts-sample/package.json
- package-lock.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/internal/deployer.ts
- packages/core/src/internal/execution/abi.ts
- packages/core/src/internal/execution/jsonrpc-client.ts
- packages/core/src/internal/execution/utils/address.ts
- packages/core/src/types/execution-events.ts
- packages/hardhat-plugin/CHANGELOG.md
- packages/hardhat-plugin/package.json
- packages/hardhat-plugin/src/index.ts
- packages/hardhat-plugin/src/load-module.ts
- packages/hardhat-plugin/src/ui/helpers/calculate-batch-display.ts
- packages/hardhat-plugin/src/ui/helpers/calculate-deployment-complete-display.ts
- packages/hardhat-plugin/src/ui/helpers/calculate-deployment-status-display.ts
- packages/hardhat-plugin/src/ui/helpers/was-anything-executed.ts
- packages/hardhat-plugin/src/ui/pretty-event-handler.ts
- packages/hardhat-plugin/src/ui/types.ts
- packages/hardhat-plugin/test/load-module.ts
- packages/hardhat-plugin/test/status.ts
- packages/hardhat-plugin/test/ui/helpers/calculate-batch-display.ts
- packages/hardhat-plugin/test/ui/helpers/calculate-deploying-module-panel-display.ts
- packages/hardhat-plugin/test/ui/helpers/calculate-deployment-complete-display.ts
- packages/hardhat-plugin/test/ui/helpers/calculate-deployment-status-display.ts
- packages/ui/package.json
- Give visual indication that there was a gas bump in `deploy` task ([#587](https://github.com/NomicFoundation/hardhat-ignition/issues/587))
- When displaying an Ethereum Address at the cli, show in checksum format ([#600](https://github.com/NomicFoundation/hardhat-ignition/issues/600))
- Show a better message when no futures were executed during a rerun ([#586](https://github.com/NomicFoundation/hardhat-ignition/issues/586))
- Less confusing message for no modules folder error ([#602](https://github.com/NomicFoundation/hardhat-ignition/issues/602))
> release: 0.11.1

- examples/complete/.eslintrc.js
- examples/ens/.eslintrc.js
- examples/sample/.eslintrc.js
- examples/ts-sample/.eslintrc.js
- examples/viem-sample/.eslintrc.js
We were seeing errors on some sample projects eslinting in vscode. This was due to a misconfiguraiont in their eslintrc that was pulling in the tsconfig wrong. Eslint then fell back to the root repo directories tsconfig, which doesn't exist - hence the error.
The solution was to remove the failing import and rely on the default.
I also excluded the eslint config file from eslint for each of the examples.
> chore: cleanup eslint config in examples

- packages/core/src/deploy.ts
- packages/hardhat-plugin-ethers/src/ethers-ignition-helper.ts
- packages/hardhat-plugin-ethers/test/default-sender.ts
- packages/hardhat-plugin-ethers/test/fixture-projects/minimal/contracts/Contracts.sol
- packages/hardhat-plugin-ethers/test/test-helpers/use-ignition-project.ts
- packages/hardhat-plugin-viem/src/viem-ignition-helper.ts
- packages/hardhat-plugin-viem/test/default-sender.ts
- packages/hardhat-plugin-viem/test/fixture-projects/minimal/contracts/Contracts.sol
Expose default sender as an option through both the viem and ethers Ignition Helper (i.e. `hre.ignition`).
Adding the tests, showed a bug in check default senders in account code due to casing differences. That has been resolved.
Resolves #639.
> feat: support changing the default sender in tests

- .github/workflows/ci.yml
- packages/core/test-integrations/fixture-projects/ci-success/contracts/Lock.sol
- packages/core/test-integrations/fixture-projects/ci-success/hardhat.config.js
- packages/core/test-integrations/fixture-projects/ci-success/ignition/modules/LockModule.js
- packages/core/test-integrations/new-api/ci/basic-success.ts
- packages/hardhat-plugin/src/ui/pretty-event-handler.ts
- packages/hardhat-plugin/test/deploy/default-sender.ts
- replaced `process.stdout` in favor of native nodejs `readline`
- also removed a redundant github workflow that ran integration tests separately since we run them as part of the top level `npm test` now
resolves #644
> Use readline in place of process.stdout

- packages/core/src/internal/execution/future-processor/handlers/monitor-onchain-interaction.ts
- packages/core/test/execution/future-processor/helpers/network-interaction-execution.ts
Small hack to give blockchain nodes time to propagate transactions before we assume them to be dropped.
Fixes #665 
Fixes #633
> Add small loop to retry checking mempool for slowly propagating blockchain nodes

- packages/core/src/internal/execution/jsonrpc-client.ts
- packages/core/src/internal/execution/types/execution-strategy.ts
- packages/core/src/types/module-builder.ts
- packages/hardhat-plugin-ethers/src/ethers-ignition-helper.ts
- packages/hardhat-plugin-viem/src/viem-ignition-helper.ts
> Add jsdoc comments for all module builder and ignition helper functions

- .github/workflows/ci.yml
- packages/hardhat-plugin-ethers/.nycrc
- packages/hardhat-plugin-viem/.nycrc
- packages/hardhat-plugin/.nycrc
- packages/ui/.nycrc
- packages/ui/package.json
Rework test coverage in `fullcheck` and apply it in github actions.
This change enforces test coverage in github actions.
> chore: cleanup coverage

- packages/core/src/internal/utils/check-automined-network.ts
- packages/core/test/utils/check-automined-network.ts
We previously guarded against a network throwing on getting `hardhat_getAutomine` as an RPC call but not `web3_clientVersion`.
There is now a guard around both, and a set of unit tests to cover the currently understood tests.
Fixes #721.
> fix: add guard to ganache automine check

- packages/core/src/internal/execution/future-processor/handlers/send-transaction.ts
- packages/core/src/internal/execution/nonce-management/json-rpc-nonce-manager.ts
- packages/core/test/execution/future-processor/utils.ts
- packages/hardhat-plugin/test/deploy/nonce-checks/revert-nonce-on-simulation-error.ts
- packages/hardhat-plugin/test/fixture-projects/minimal/contracts/FailureCalls.sol
Fixes what was thought to be a race condition by reverting the allocated nonce after a simulated transaction fails.
Resolves #676
> Revert allocated nonce after simulation fails

- packages/core/src/internal/execution/future-processor/helpers/network-interaction-execution.ts
- packages/hardhat-plugin/test/deploy/gas-estimation.ts
- packages/hardhat-plugin/test/fixture-projects/minimal/contracts/Fails.sol
Resolves #627 
Simulating calls doesn't require any gas, but added a test anyways just to cover the case.
> Added a test to ensure simulation errors are displayed

- packages/hardhat-plugin-ethers/src/ethers-ignition-helper.ts
- packages/hardhat-plugin-viem/src/viem-ignition-helper.ts
- packages/hardhat-plugin/src/helpers.ts
- fixed an oversight where the ethers/viem Ignition helpers wouldn't write the `deployments` directory even when on a non-ephemeral network
- added the ability to set a custom `deploymentId` via the ethers/viem Ignition helpers
resolves #703
> Allow test helpers to write deployments dir

- packages/core/src/internal/execution/jsonrpc-client.ts
We were previously relying on an implicit blocktag.
Fixes #715.
> fix: provide all params to `eth_getCode`

- .github/workflows/ci.yml
- examples/complete/package.json
- examples/ens/package.json
- examples/sample/package.json
- examples/ts-sample/package.json
- examples/viem-sample/package.json
- package-lock.json
- package.json
- packages/core/package.json
- packages/core/src/internal/execution/jsonrpc-client.ts
- packages/hardhat-plugin-ethers/package.json
- packages/hardhat-plugin-viem/package.json
- packages/hardhat-plugin/package.json
EDR now supports all the complicated test setup moves that where required by the Ignition end to end test suite.
> chore: revert dev dependency to latest hardhat

- CONTRIBUTING.md
Add an imprint on the end of any release message, and show a template in the publishing instructions in `./CONTRIBUTING.md`.
> chore: update publishing to include hiring imprint

- packages/hardhat-plugin/src/index.ts
- packages/hardhat-plugin/src/ui/helpers/calculate-batch-display.ts
- packages/hardhat-plugin/src/ui/pretty-event-handler.ts
- packages/hardhat-plugin/src/ui/types.ts
- packages/hardhat-plugin/test/ui/helpers/calculate-batch-display.ts
- packages/hardhat-plugin/test/ui/helpers/calculate-deploying-module-panel-display.ts
- packages/hardhat-plugin/test/ui/pretty-event-handler.ts
fixes #720 
Waiting for confirmation from ledger device
Ledger device confirmed and transaction was sent to network (waiting for block confirmations before continuing)
Previous ledger messages are removed when execution continues (and are replaced by current ledger messages when needed)
All ledger messages removed for final status display
> Integrating hardhat-ledger support

- package-lock.json
- packages/core/src/internal/execution/jsonrpc-client.ts
This is to add support for chains that have been set up with zero base fee, such as a private instance of blockchains using Besu.
> Support zero gas fee chains

- packages/core/src/deploy.ts
- packages/core/src/internal/execution/jsonrpc-client.ts
- packages/core/test-integrations/new-api/internal/new-execution/jsonrpc-client.ts
- packages/hardhat-plugin-ethers/src/ethers-ignition-helper.ts
- packages/hardhat-plugin-viem/src/viem-ignition-helper.ts
- packages/hardhat-plugin/src/index.ts
- packages/hardhat-plugin/src/type-extensions.ts
- packages/hardhat-plugin/test/config.ts
- packages/hardhat-plugin/test/fixture-projects/with-config/hardhat.config.js
- adds `maxPriorityFeePerGas` to user config
- returns legacy fees when deploying to Polygon
- manually tested and confirmed that this does indeed fix deployments on Polygon
resolves #728
> Custom logic for Polygon and support for `maxPriorityFeePerGas`

- packages/core/src/internal/execution/jsonrpc-client.ts
- packages/core/test-integrations/new-api/internal/new-execution/jsonrpc-client.ts
This commit updates the gas fee configuration logic to accommodate the BNB Chain (chainId 56). While the BNB Network supports EIP-1559, it reports a `baseFeePerGas` of zero(https://github.com/bnb-chain/bsc/issues/2062). This adjustment ensures that transactions on the BNB Chain do not mistakenly receive a max fee configuration of zero, which is not appropriate despite the reported base fee. This change maintains the functionality for other chains such as Polygon (chainId 137) that require legacy gasPrice fees, and excludes only BNB Chain from the zero max fee logic. This is crucial for proper transaction fee handling on networks supporting EIP-1559 but reporting a base fee of zero.
Deployments on the BNB Chain were failing. The required tip for transactions should be n wei, but because …
> Exclude BNB Chain from zero fee configuration in gas fee logic

- packages/core/src/internal/execution/jsonrpc-client.ts
- packages/core/test-integrations/new-api/internal/new-execution/jsonrpc-client.ts
Add comment and more explicit assertion.
> test: tweak BNB chain test

- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/core/src/internal/execution/jsonrpc-client.ts
- packages/core/test-integrations/new-api/internal/new-execution/jsonrpc-client.ts
- packages/hardhat-plugin-ethers/CHANGELOG.md
- packages/hardhat-plugin-ethers/package.json
- packages/hardhat-plugin-viem/CHANGELOG.md
- packages/hardhat-plugin-viem/package.json
- packages/hardhat-plugin/CHANGELOG.md
- packages/hardhat-plugin/package.json
- Exclude BNB Chain from zero fee configuration in gas fee logic, thanks @magicsih ([#755](https://github.com/NomicFoundation/hardhat-ignition/pull/755))
> Chore: bump version to 0.15.3

- .gitignore
- packages/core/src/internal/execution/utils/address.ts
- packages/core/src/internal/reconciliation/helpers/reconcile-arguments.ts
- packages/core/test/reconciliation/futures/reconcileArtifactContractDeployment.ts
- packages/core/test/reconciliation/futures/reconcileNamedContractCall.ts
- packages/core/test/reconciliation/futures/reconcileNamedContractDeployment.ts
- packages/core/test/reconciliation/futures/reconcileNamedStaticCall.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
The problem raised by issue #745 is that currently ignition will fail to reconcile the address param `0xaaa...` if it has been changed to `0xAaa...` or, more specifically, if the case of the new address doesn't perfectly match the previously executed address. 
This makes sense as a bug to fix, but there is a bit of a design decision to be made around what solution we decide on. The solution I opted for, and what is currently in this PR, is the following logic:
- `0xaaa...` + `0xAAA...` reconciles ✅
- `0xaaa...` + `0xAaa...` does not reconcile ❌
The reason for this choice is because it follows the same rules that ethers uses for their checksum and address-checking code. 
An alternative approach would be to cast every address to lowercase before checking equality, which would allow for the …
> Reconcile addresses with mismatched casings

- packages/core/src/internal/errors-list.ts
- packages/core/src/internal/execution/future-processor/handlers/send-transaction.ts
- packages/core/src/internal/execution/future-processor/helpers/decode-simulation-result.ts
- packages/core/src/internal/execution/future-processor/helpers/network-interaction-execution.ts
- packages/core/test/execution/future-processor/helpers/network-interaction-execution.ts
- packages/hardhat-plugin/src/utils/shouldBeHardhatPluginError.ts
- packages/hardhat-plugin/test/deploy/rerun/rerun-after-kill.ts
This PR includes a few changes:
1. adds three new IgnitionError types
- insufficient funds for transfer (i.e. `m.send`)
- insufficient funds for deployment
- catch-all error for any other error
2. detects which error is thrown by the provider and throws the appropriate error above
3. refactored `sendTransactionForOnchainInteraction` and `sendTransaction` slightly to make the former more testable
4. wrote unit tests providing full coverage for `sendTransactionForOnchainInteraction`
resolves #750
> Display better error messages for insufficient funds

- packages/core/src/internal/execution/jsonrpc-client.ts
- packages/core/test-integrations/new-api/internal/new-execution/jsonrpc-client.ts
Following on from #755, Updated the gas fee configuration logic to accommodate the BNB Test Chain (chainId 97) to exclude from zero fee configuration.
Resolves #763
> Exclude BNB Test Chain from zero fee configuration in gas fee logic

- packages/core/src/verify.ts
- packages/core/test/verify.ts
resolves #770 
simple fix for circular imports (or enormous import trees)
> Handle circular imports in verify loop

- packages/core/src/internal/utils/identifier-validators.ts
- packages/core/test/validations/identifier-validators.ts
fixes #762 
Adjusted the regex to be more strict in general as there were some invalid cases that were being allowed with the previous regex (even though they would be caught later in the validation process). 
Added tests for relevant passing and failing cases
--
I also verified manually that square brackets are allowed in filenames in both unix and windows systems, so that is a non-issue.
> Adjust regex to handle square brackets

- packages/hardhat-plugin-viem/src/ignition-module-results-to-viem-contracts.ts
- packages/hardhat-plugin-viem/src/viem-ignition-helper.ts
- Fix a typo 
- Replace 'this' with the class in a static method. For more information, refer to: https://github.com/mysticatea/eslint-plugin/blob/master/docs/rules/no-this-in-static.md.
I have a question. I'm interested in contributing to Hardhat and would like to know what I can to do.
> chore:Fix the typo and replace 'this' with the class in a static method

- packages/hardhat-plugin/src/index.ts
I found debug logging errors produced during interaction with `hardhat-ledger` plugin helpful during the development of https://github.com/NomicFoundation/hardhat/pull/5578. I think it might be useful to others, too, if they have to work with this part of the codebase in the future.
> chore: debug log hardhat ledger communication errors

- packages/hardhat-plugin/src/index.ts
- packages/hardhat-plugin/test/deploy/writeLocalhost.ts
This is an alternative to #809 to also solve #791
> add writeLocalhostDeployment to deploy command

- packages/ui/package.json
- packages/ui/src/components/mermaid.tsx
- packages/ui/src/main.css
- packages/ui/src/pages/visualization-overview/components/deployment-flow.tsx
- pnpm-lock.yaml
resolves https://github.com/NomicFoundation/hardhat-ignition/issues/806
resolves https://github.com/NomicFoundation/hardhat-ignition/issues/807
- using `svg-pan-zoom` library to zoom and pan mermaid diagram
- set `maxTextSize` to `5e5` instead of the default of `5e4`
> SVG zoom for visualization graph

- examples/fee-tester/.eslintrc.js
- examples/fee-tester/.gitignore
- examples/fee-tester/.prettierignore
- examples/fee-tester/README.md
- examples/fee-tester/contracts/FeeTester.sol
- examples/fee-tester/hardhat.config.js
- examples/fee-tester/ignition/modules/FeeTesterModule.js
- examples/fee-tester/package.json
- packages/core/src/deploy.ts
- packages/core/src/internal/defaultConfig.ts
- packages/core/src/internal/deployer.ts
- packages/core/src/internal/execution/execution-engine.ts
- packages/core/src/internal/execution/future-processor/future-processor.ts
- packages/core/src/internal/execution/future-processor/handlers/monitor-onchain-interaction.ts
- packages/core/src/internal/execution/jsonrpc-client.ts
- packages/core/src/types/deploy.ts
- packages/core/src/types/execution-events.ts
- packages/core/test/execution/future-processor/helpers/network-interaction-execution.ts
- packages/core/test/execution/future-processor/utils.ts
- packages/hardhat-plugin/src/index.ts
- packages/hardhat-plugin/src/type-extensions.ts
- packages/hardhat-plugin/src/ui/pretty-event-handler.ts
- packages/hardhat-plugin/src/ui/types.ts
- packages/hardhat-plugin/test/config.ts
- packages/hardhat-plugin/test/fixture-projects/with-config/hardhat.config.js
- packages/hardhat-plugin/test/test-helpers/use-ignition-project.ts
- packages/hardhat-plugin/test/ui/helpers/calculate-batch-display.ts
- packages/hardhat-plugin/test/ui/helpers/calculate-deploying-module-panel-display.ts
Resolves https://github.com/NomicFoundation/hardhat-ignition/issues/724
- `examples/fee-tester` to assist with manual testing
- `gasPrice` and `disableFeeBumping` config fields added
- hardcoded gasPrice value for Polygon Amoy testnet
> Update L2 fees logic

- packages/hardhat-plugin/src/hardhat-artifact-resolver.ts
- packages/hardhat-plugin/test/fixture-projects/multiple-contracts-with-same-name/contracts/Rocket1.sol
- packages/hardhat-plugin/test/fixture-projects/multiple-contracts-with-same-name/contracts/Rocket2.sol
- packages/hardhat-plugin/test/fixture-projects/multiple-contracts-with-same-name/hardhat.config.js
- packages/hardhat-plugin/test/module-api/fully-qualified-names.ts
In the artifact resolver detect whether a FQN is being used to refer to the contract and use Hardhat's own build info resolution method (which assumes an FQN).
This is now covered with an additional integration test for repos with multiple contracts with the same name in different files and an Ignition module where those contracts are referred to by FQNs.
Fixes #778.
> fix: fqn resolution of artifacts

- packages/core/src/internal/execution/jsonrpc-client.ts
A user in discord reported an issue using ignition on opBNB and its testnet. After looking into it, these chains required the same exclusions in our gas logic as the layer one BNB chains. I added them to the logic and tested manually that this did indeed fix the bug.
> Add opBNB and its testnet to the BNB exclusions in gas logic

- packages/core/src/internal/utils/resolve-module-parameter.ts
- packages/core/src/internal/validation/futures/validateArtifactContractAt.ts
- packages/core/src/internal/validation/futures/validateArtifactContractDeployment.ts
- packages/core/src/internal/validation/futures/validateNamedContractAt.ts
- packages/core/src/internal/validation/futures/validateNamedContractCall.ts
- packages/core/src/internal/validation/futures/validateNamedContractDeployment.ts
- packages/core/src/internal/validation/futures/validateNamedEncodeFunctionCall.ts
- packages/core/src/internal/validation/futures/validateNamedStaticCall.ts
- packages/core/src/internal/validation/futures/validateSendData.ts
- packages/core/src/internal/validation/utils.ts
- packages/core/test/call.ts
- packages/core/test/contract.ts
- packages/core/test/contractAt.ts
- packages/core/test/contractAtFromArtifact.ts
- packages/core/test/contractFromArtifact.ts
- packages/core/test/encodeFunctionCall.ts
- packages/core/test/execution/future-processor/helpers/build-initialize-message-for.ts
- packages/core/test/send.ts
- packages/core/test/staticCall.ts
- packages/hardhat-plugin/test/module-parameters.ts
Default values for parameters masked the test cases for our global parameters feature.
This commit adds additional tests for parameters without default values and enhances the validations to support Global Parameters as an option.
> fix: add additional validation for global parameters

- packages/core/src/ignition-module-serializer.ts
- packages/core/src/internal/batcher.ts
- packages/core/src/internal/module-builder.ts
- packages/core/src/internal/module.ts
- packages/core/src/internal/utils/adjacency-list-converter.ts
- packages/core/src/types/module-builder.ts
- packages/core/src/types/module.ts
- packages/core/src/types/serialization.ts
- packages/core/test/batcher.ts
- packages/core/test/call.ts
- packages/core/test/contract.ts
- packages/core/test/contractAt.ts
- packages/core/test/contractAtFromArtifact.ts
- packages/core/test/contractFromArtifact.ts
- packages/core/test/encodeFunctionCall.ts
- packages/core/test/library.ts
- packages/core/test/libraryFromArtifact.ts
- packages/core/test/send.ts
- packages/core/test/staticCall.ts
- packages/core/test/types/module.ts
- packages/ui/examples/ComplexModule.js
- packages/ui/src/main.css
- packages/ui/src/pages/visualization-overview/components/deployment-flow.tsx
- packages/ui/src/pages/visualization-overview/components/future-header.tsx
- packages/ui/src/utils/to-mermaid.ts
> Allow ignition modules as a dependency for futures

- packages/hardhat-plugin-ethers/src/ethers-ignition-helper.ts
- packages/hardhat-plugin-viem/src/viem-ignition-helper.ts
- packages/hardhat-plugin/src/helpers.ts
Resolves https://github.com/NomicFoundation/hardhat-ignition/issues/839
Tested whatever situations I could think of and everything looked okay. Below is a sample output of a run on a local non-ephemeral network with an immediate follow up run that deploys nothing:
> Enable ignition UI for deployments via hardhat scripts

- packages/core/src/list-transactions.ts
- packages/core/src/types/list-transactions.ts
- packages/core/test/list-transactions.ts
- packages/hardhat-plugin/src/index.ts
- packages/hardhat-plugin/src/type-extensions.ts
- packages/hardhat-plugin/src/ui/helpers/calculate-list-transactions-display.ts
resolves https://github.com/NomicFoundation/hardhat-ignition/issues/838
> Add link to transactions list command output

- packages/hardhat-plugin-ethers/src/ethers-ignition-helper.ts
- packages/hardhat-plugin-viem/src/viem-ignition-helper.ts
- packages/hardhat-plugin/src/helpers.ts
- packages/hardhat-plugin/src/index.ts
- packages/hardhat-plugin/src/utils/read-deployment-parameters.ts
resolves https://github.com/NomicFoundation/hardhat-ignition/issues/844
> Allow importing module parameters with filepath in scripts
